### ISSUE TITLE
Was not able to run train.lua on GPU

### ISSUE THREAD

**Issue by wael34218** [OpenNMT/OpenNMT#102]
I am having hard time making train.lua work using GPU. I am running the following command:

CUDA_VISIBLE_DEVICES=1 th train.lua -data ../wmt15-de-en/wmt15-all-en-de-train.t7 -save_model ../wmt15-de-en/wmt15-all-en-de -gpuid 0

It runs utilizing the CPU (`htop` displays 8 cores on 99% usage) and `nvidia-smi` displays zero GPU processes and no memory usage. I made sure that Torch GPU libraries are installed correctly using:
luajit -lcutorch
luajit -lcunn

What should I do to make it work using GPU?

Environment:
Cuda compilation tools, release 8.0, V8.0.44
Linux simo 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
VGA compatible controller: NVIDIA Corporation GK110B [GeForce GTX TITAN Black]
cuDNN 5.1

**Comment by guillaumekln** [comment]
As stated in the `-gpuid` option description, its value is 1-indexed. So you should run:

```
CUDA_VISIBLE_DEVICES=1 th train.lua -data ../wmt15-de-en/wmt15-all-en-de-train.t7 -save_model ../wmt15-de-en/wmt15-all-en-de -gpuid 1
```

or simply:


```
th train.lua -data ../wmt15-de-en/wmt15-all-en-de-train.t7 -save_model ../wmt15-de-en/wmt15-all-en-de -gpuid 1
```

**Comment by wael34218** [comment]
Thanks! Now I am encountering another error:

If I run it without `CUDA_VISIBLE_DEVICES=1` I get:
```
$ th train.lua -data ../wmt15-de-en/wmt15-all-en-de-train.t7 -save_model ../wmt15-de-en/wmt15-all-en-de -gpuid 1
[01/30/17 13:36:25 INFO] Using GPU(s): 1
Segmentation fault (core dumped)
```

Else I get:
```
$ CUDA_VISIBLE_DEVICES=1 th train.lua -data ../wmt15-de-en/wmt15-all-en-de-train.t7 -save_model ../wmt15-de-en/wmt15-all-en-de -gpuid 1
THCudaCheck FAIL file=/home/user/OpenNMT/torch/extra/cutorch/lib/THC/THCGeneral.c line=66 error=38 : no CUDA-capable device is detected
/home/user/OpenNMT/torch/install/bin/luajit: .../user/OpenNMT/torch/install/share/lua/5.1/trepl/init.lua:389: cuda runtime error (38) : no CUDA-capable device is detected at /home/user/OpenNMT/torch/extra/cutorch/lib/THC/THCGeneral.c:66
```

**Comment by guillaumekln** [comment]
It is `CUDA_VISIBLE_DEVICES=0` (sorry, I quickly edited my comment but not quick enough it seems) but you actually don't need this flag as you have only one GPU.

As for the error, you should certainly reinstall Torch from scratch or check your driver installation if it persists. It does not appear to be related to OpenNMT.

**Comment by wael34218** [comment]
Sure will do that! Thanks mate!

**Comment by wael34218** [comment]
Yes reinstalling Torch from scratch worked! Thanks again for your quick responses! Much appreciated!
