### ISSUE TITLE
Ability to use existing models on CPU

### ISSUE THREAD

**Issue by prafiles** [OpenNMT/OpenNMT#103]
Hi!

There are a couple of models on the OpenNMT website, but I'm unable to find a way to port the existing GPU trained models to run just on CPU. Also since these models were trained on Titan X, I've been running into issues trying to run it on small GPUs as well. 

If this is not an issue, please point me into the correct direction. It'd be great help.

**Comment by guillaumekln** [comment]
Which model are you referring in particular? If the model filename ends with `_release.t7` it means it is already CPU compatible (which is the case for all NMT models on the website).

**Comment by prafiles** [comment]
The model I used is for text summarisation:
https://s3.amazonaws.com/opennmt-models/sum_model_epoch11_14.62.t7

I dont want to train the model, though that works fine. I just want to use it. Hence went straight for generating summary via the git example for the directory.

**Comment by guillaumekln** [comment]
@srush This model should be compatible with CPU. Can you update the link?

**Comment by vince62s** [comment]
we have the epoch7_14.69.t7 model available. if you want we can release it and upload the CPU version somewhere.

**Comment by prafiles** [comment]
Thank you! That will be great!

**Comment by vince62s** [comment]
here you go https://s3.amazonaws.com/opennmt-models/textsum_epoch7_14.69_release.t7
please close this issue. thanks.
