### ISSUE TITLE
Single translation model of multiple language pairs

### ISSUE THREAD

**Issue by xiamx** [OpenNMT/OpenNMT#104]
Hi,

This is an awesome project.

On your technical report, it is shown in Table 2 that you train a single translation model using multiple language pairs. Could you shed some light on how to format the training input? 

Thanks

**Comment by guillaumekln** [comment]
Hi,

You'll find more details in this forum post: http://forum.opennmt.net/t/training-romance-multi-way-model/86

**Comment by xiamx** [comment]
Thanks @guillaumekln  👍
