### ISSUE TITLE
-replace_unk  -phrase_table pb.txt lost some vocabulary

### ISSUE THREAD

**Issue by netxiao** [OpenNMT/OpenNMT#108]
**pb.txt contents:**

freebsd|||freekkk
mysql|||mkkk
bitterness|||bkkk

**translate script**
`th translate.lua -replace_unk  -phrase_table pb.txt -model  model_epoch5_9.47_release.t7  -src t.txt   -output result.txt`

**t.txt contents (src sentences list)**
_bitterness_ fed on the man who had made the world laugh .
automatic properties and structures do not mix ?
_mysql_  great circle distance

**result.txt contents(tgt sentences list)**
fed on on . 的 人
自动 属性 和 结构 不 混合 ?
great circle

bitterness AND mysql has been lost.

I trace to **onmt/translate/Translator.lua** file, found in
 `function Translator:buildTargetWords(pred, src, attn)'

       ' local source = src[maxIndex[1]] 
        print(source);'

**print source words:**
fed
on
on
.
LOST _bitterness_ 

Please help me!

**Comment by guillaumekln** [comment]
That is a direct result of the attention mechanism that is used. When translating:

> bitterness fed on the man who had made the world laugh .

your model first generated:

> \<unk> \<unk> \<unk> \<unk> 的 人

As you used the `-replace_unk` option, it then tried to replace these unknown words by looking at source words with the highest attention value. In your case it was respectively:

* fed
* on
* on
* .

and as none of these appeared in the phrase table, they were simply copied in the target.

---

How many data do you have? These "alignment" issues are common when the model is not fully trained or has too few data to predict sequences with high confidence.

**Comment by netxiao** [comment]
many thanks!

How to direct output origin UNK word  like moses? 

My training script as below:

**4,483,244** parallel sentences,14 epoch.

**preprocess script:**
`th preprocess.lua -train_src data/train/train.src.tok -train_tgt data/train/train.trg.tok -valid_src data/test/test.src -valid_tgt  data/test/test.trg  -src_seq_length 50  -tgt_seq_length 50 -src_vocab_size 70000 -tgt_vocab_size 70000  -report_every 5000 -save_data data/save`

**train script:**
th train.lua -gpuid 1 -layers 2  -max_batch_size 64 -rnn_size 500 -optim adam -learning_rate 0.0002  -end_epoch 13  -save_every 3000 -data data/save-train.t7 -save_model model

**Comment by guillaumekln** [comment]
> How to direct output origin UNK word like moses?

There is no such mechanism at the moment.

---

Maybe you should start a comparative training with the default SGD optimizer. We didn't always get good results with alternative optimizers.

**Comment by netxiao** [comment]
thanks!
