### ISSUE TITLE
use release cpu model got error:unknown Torch class <torch.CudaTensor>

### ISSUE THREAD

**Issue by netxiao** [OpenNMT/OpenNMT#109]
my runtime env: **torch7, lua5.2**
**release model script is:**
`th tools/release_model.lua -force -model   model_epoch14_8.51.t7  -gpuid 1`

**when I run translate script:**
`th translate.lua  -model  model_epoch14_8.51_release.t7 -src s.txt   -output result.txt`
**I got error informations:**
```
[02/06/17 16:38:18 INFO] Loading 'model_epoch14_8.51_release.t7'...
work/openNMT/torch/install/share/lua/5.2/torch/File.lua:343: unknown Torch class <torch.CudaTensor>
stack traceback:
        [C]: in function 'error'
        .../work/openNMT/torch/install/share/lua/5.2/torch/File.lua:343: in function 'readObject'
        .../work/openNMT/torch/install/share/lua/5.2/torch/File.lua:369: in function 'readObject'
        .../work/openNMT/torch/install/share/lua/5.2/torch/File.lua:369: in function 'readObject'
        .../work/openNMT/torch/install/share/lua/5.2/torch/File.lua:369: in function 'readObject'
        .../work/openNMT/torch/install/share/lua/5.2/torch/File.lua:369: in function 'readObject'
        .../work/openNMT/torch/install/share/lua/5.2/torch/File.lua:409: in function 'load'
        ./onmt/translate/Translator.lua:35: in function '__init'
        .../work/openNMT/torch/install/share/lua/5.2/torch/init.lua:91: in function 'new'
        translate.lua:78: in function 'main'
        translate.lua:197: in main chunk
        [C]: in function 'dofile'
        ...nNMT/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: in ?
```
use gpu mode is OK.
please help!

**Comment by guillaumekln** [comment]
What training options did you use?

**Comment by netxiao** [comment]
my training script as below:
`th train.lua -gpuid 1 -layers 2  -max_batch_size 64 -rnn_size 500 -optim adam -learning_rate 0.0002  -end_epoch 13  -save_every 3000 -data data/save-train.t7 -save_model model `

**Comment by guillaumekln** [comment]
Can you make sure that you are using an up-to-date `release_model.lua` script? I suspect that [this fix](https://github.com/OpenNMT/OpenNMT/commit/d7a76e901405044dece219baaa8c1ebfbaf09f1d) is missing.

**Comment by netxiao** [comment]
I use the latest version of `release_model.lua`  script,  I also tried using multiple older versions, but the problem persists.

**The training process is as follows:**
When training  to epoch5, interrupted it, and then created release model: `model_epoch5_9.47_release.t7`

**`model_epoch5_9.47_release.t7` can work fine in cpu mode**

and then continue to train, my resuming training script as below:

`th train.lua -train_from  model_epoch5_9.47.t7 -start_epoch 6 -continue   -gpuid 1 -layers 2  -max_batch_size 64 -rnn_size 500 -optim adam -learning_rate 0.0002  -end_epoch 14  -save_every 5000 -data data/save-train.t7 -save_model model`

When the training is over, and then run:

` th tools/release_model.lua -force -model model_epoch14_8.51.t7 -gpuid 1`

run translate script:

`th translate.lua -model model_epoch14_8.51_release.t7 -src s.txt -output result.txt`

I got error informations:

```
work/openNMT/torch/install/share/lua/5.2/torch/File.lua:343: unknown Torch class <torch.CudaTensor>
stack traceback:
```
I also tried to use lua51, lua52, but the problem remains.

**Comment by guillaumekln** [comment]
Thank you. I was able to reproduce the issue with the useful information you shared.

I fixed the root of the issue so that new trainings will not be impacted by it. On you side, you could:

1. Update the code with the fix and start another retraining with the latest model. The next saved model should work on the CPU after a release.
**OR**
2. Add the following line in `release_model.lua`:

```lua
checkpoint.options.optim_states = nil
```

just after the line 61:

```lua
checkpoint.info = nil
```

**Comment by netxiao** [comment]
thanks for your great help!
