### ISSUE TITLE
Models link is broken

### ISSUE THREAD

**Issue by ksslng** [OpenNMT/OpenNMT#11]
The models link at the end of the readme is broken and I couldn't find a working one.

**Comment by srush** [comment]
Oh sorry, models are in transit. Coming soon.

**Comment by srush** [comment]
Fixed.

**Comment by nkrot** [comment]
This link to German-English found on http://opennmt.net//Models/ is also broken
`https://s3.amazonaws.com/opennmt-models/onmt_baseline_wmt15-all.de-en_epoch13_8.98_release.t7`
