### ISSUE TITLE
How to train data for domain adaptation

### ISSUE THREAD

**Issue by netxiao** [OpenNMT/OpenNMT#110]
I'm looking for some information on how to use domain adaptation like moses.

How to combine in-domain and out-domain models?

thanks!

**Comment by guillaumekln** [comment]
Take a look at this paper: https://arxiv.org/pdf/1612.06141.pdf

The main idea is to first train a generic model then retrain it on in-domain data (with the `-train_from` option). Experiments show that the model can be quickly adapted to a specific domain

Also, as the vocabulary has to be same, BPE is usually used.

**Comment by netxiao** [comment]
thanks for your help!
