### ISSUE TITLE
declareOpts nil?

### ISSUE THREAD

**Issue by jonathanglima** [OpenNMT/OpenNMT#117]
Hey, yesterday I checked out an old version of OpenNMT repo in my machine and the following error appeared. I really don't know even where to start looking for the error. I'm using the master branch and declareOpts inside onmt/utils/Logger.lua is there, exactly as the code in the master branch.

```
$ th preprocess.lua -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo
/home/ubuntu/torch/install/bin/luajit: preprocess.lua:35: attempt to call field 'declareOpts' (a nil value)
stack traceback:
        preprocess.lua:35: in main chunk
        [C]: in function 'dofile'
        ...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670
```

**Comment by guillaumekln** [comment]
Hi!

Which version did you checked-out? Are you still on this version or did you revert back to the latest commit on master?

**Comment by jonathanglima** [comment]
Reverted to latest commit on master. But I mentioned the old version because it might be an important Info to link to an error such as an old version of torch, lua or something like that. But my current repo is clean:

`$ git pull
Already up-to-date.`

`$ git status
On branch master
Your branch is up-to-date with 'origin/master'.`

**Comment by guillaumekln** [comment]
Did you previously install OpenNMT with `luarocks make rocks/opennmt-scm-1.rockspec`?

**Comment by jonathanglima** [comment]
Yeah, that's even in my bash history. Everything was up and running before I pulled the updates =(

**Comment by guillaumekln** [comment]
You should either remove the rock (`luarocks remove opennmt`) or reinstall the new version (`luarocks make rocks/opennmt-scm-1.rockspec`).

**Comment by jonathanglima** [comment]
That did the trick! Thanks a lot
