### ISSUE TITLE
How to get attention vectors in Training stage ?

### ISSUE THREAD

**Issue by wsnooker** [OpenNMT/OpenNMT#124]
Hi, I want to get the attention vectors from the attention modules in training stage. But I cann't find the info in `train.lua`.

**Comment by guillaumekln** [comment]
Currently, attention vectors are not directly outputted by the model. However, we put [a flag](https://github.com/OpenNMT/OpenNMT/blob/master/onmt/modules/GlobalAttention.lua#L47) on it so you can query the network to find it. For example, to get the attention vector at timestep `t`:

```lua
local attention
decoder:net(t):apply(function (m)
  if m.name == 'softmaxAttn' then
    attention = m.output
  end
end)
```

**Comment by wsnooker** [comment]
Sorry to trouble you again.

I am a newer to `lua` and it is hard for me to get the content of `train.lua`.

I want to get the tgt words' attention vectors to src words (not ids).

Could you give me a clear info about how to get that in `train.lua` ?

**Comment by guillaumekln** [comment]
Why do you need them at training time?

**Comment by wsnooker** [comment]
In my task, the nmt is used to train a model for Homologous translation. The goal is to rewrite the query. But I also want to get the alignment word in the train data based on fine trained model which will be used as the relevance word table.

Can you give me a hand for that ?

**Comment by guillaumekln** [comment]
Here is a starter for you:

```diff
diff --git a/train.lua b/train.lua
index 3aadc02..13f28b0 100644
--- a/train.lua
+++ b/train.lua
@@ -177,6 +177,23 @@ local function eval(model, criterion, data)
   return math.exp(loss / total)
 end
 
+local function printAttention(batch, attention, dicts)
+  for b = 1, batch.size do
+    for t = 1, batch.targetLength do
+      if batch.targetOutput[t][b] == onmt.Constants.EOS then
+        break
+      end
+
+      _G.logger:info('%s', dicts.tgt.words:lookup(batch.targetOutput[t][b]))
+      for i = 1, batch.sourceLength do
+        _G.logger:info('  %.4f %s',
+                       attention[t][b][i],
+                       dicts.src.words:lookup(batch.sourceInput[i][b]))
+      end
+    end
+  end
+end
+
 local function trainModel(model, trainData, validData, dataset, info)
   local params, gradParams = {}, {}
   local criterion
@@ -252,6 +269,19 @@ local function trainModel(model, trainData, validData, dataset, info)
       local encStates, context = _G.model.encoder:forward(batch)
       _G.profiler:stop("encoder.fwd"):start("decoder.fwd")
       local decOutputs = _G.model.decoder:forward(_G.batch, encStates, context)
+
+      local attention = {}
+
+      for t = 1, batch.targetLength do
+        _G.model.decoder:net(t):apply(function (m)
+          if m.name == 'softmaxAttn' then
+            table.insert(attention, m.output)
+          end
+        end)
+      end
+
+      printAttention(batch, attention, dataset.dicts)
+
       _G.profiler:stop("decoder.fwd"):start("decoder.bwd")
       local encGradStatesOut, gradContext, loss = _G.model.decoder:backward(_G.batch, decOutputs, _G.criterion)
       _G.profiler:stop("decoder.bwd"):start("encoder.bwd")
```

After each iteration it gathers attention vectors for all timesteps and print the attention of each target word relative to source words.

**Comment by wsnooker** [comment]
Greate, the problem has been solved. Thanks you.
