### ISSUE TITLE
LSTM code bug

### ISSUE THREAD

**Issue by helson73** [OpenNMT/OpenNMT#127]
Currently, line 107, 108 is:
```
  local i2h = nn.Linear(inputSize, 4 * hiddenSize)(x)
  local h2h = nn.Linear(hiddenSize, 4 * hiddenSize)(prevH)
```
however, line 108 should be changed to
`  local h2h = nn.Linear(hiddenSize, 4 * hiddenSize, false)(prevH)`
Otherwise, there would be two bias.
Similar problem in 'GRU.lua' line 127.

**Comment by guillaumekln** [comment]
From @jsenellart-systran:

> for reference, we know that there is a redundancy here - but we added it for being equivalent with cudnn.LSTM.

**Comment by helson73** [comment]
@guillaumekln So it's for compatibility. Why don't directly use cudnn.LSTM? Because of memory consumption?

**Comment by jsenellart-systran** [comment]
@helson73 - cudnn.LSTM is coming in the next release, memory consumption is a higher indeed but we have ~20-25% speed improvement (on seq2seq model) - note also that it does not support all of the features we have, for instance the `brnn_merge sum`.

**Comment by guillaumekln** [comment]
And we still need the other implementation for CPU training/translation that's why we want them to be equivalent.

**Comment by helson73** [comment]
@jsenellart-systran Nvidia official website reported that cudnn could speed up RNN up to 600%. In our case, large network size neutralized speed improvement from massive parallelism?

**Comment by jsenellart-systran** [comment]
from my experiments, the speed-up on the encoder itself is about x2.5 - but the effect reduces for larger network. Also - we have some layers around (word embedding before and the complete decoder after) - so the global impact is smaller.

**Comment by helson73** [comment]
@jsenellart-systran Seems like in decoder cudnn cannot be used due to input of each time step depends on previous hidden states. Shortcoming is obvious, cudnn.LSTM is far too away from flexibility, which forces users feed networks with fixed sequence-batch data. But still, improvements are encouraging. Maybe further improvements require work beyond torch community : e.g. improve cudnn itself.

**Comment by jsenellart-systran** [comment]
@helson73 yes - indeed, we cannot use cudnn.LSTM for decoding because of input feeding - the support will only be for the encoder.
