### ISSUE TITLE
How could I get the score of the attention while translate?

### ISSUE THREAD

**Issue by anoidgit** [OpenNMT/OpenNMT#128]
I'm trying to analyse the alignment of the model, and I need the attention score, but I not sure whether this line code [`local softmaxOut = self.decoder.softmaxAttn.output`](https://github.com/OpenNMT/OpenNMT/blob/master/onmt/translate/DecoderAdvancer.lua#L80) was the output of the attention module.
Thank you for your help.

**Comment by guillaumekln** [comment]
It is but the attention is directly outputted by the translator. See:

https://github.com/OpenNMT/OpenNMT/blob/master/onmt/translate/Translator.lua#L279

**Comment by anoidgit** [comment]
Thank you for your help, then I know how to get it. @guillaumekln

**Comment by ratishsp** [comment]
Hi @guillaumekln, could you please paste the code where the attention is directly outputted by the translator.

**Comment by guillaumekln** [comment]
Here is the updated location:

https://github.com/OpenNMT/OpenNMT/blob/v0.9.7/onmt/translate/Translator.lua#L577

For example, translate.lua is using it [here](https://github.com/OpenNMT/OpenNMT/blob/v0.9.7/translate.lua#L269) to dump the attention vectors when the option `-save_attention` is set.
