### ISSUE TITLE
Unable to train the model with GPU

### ISSUE THREAD

**Issue by mdasadul** [OpenNMT/OpenNMT#129]
I was using ONMT for training several models as I pull the changes from master branch It seems to me the training using GPU is broken. Training in CPU though still working.
![gpu_issue](https://cloud.githubusercontent.com/assets/8009589/22994377/c1962e4a-f394-11e6-8c29-3f42e1adee24.PNG)

**Comment by guillaumekln** [comment]
Can you update your Torch installation?

**Comment by mdasadul** [comment]
I will ask my system admin to update your Torch Installation. Thanks

**Comment by guillaumekln** [comment]
This was reproduced on a relatively recent Torch version so it should be fixed.

**Comment by guillaumekln** [comment]
My bad, some modules were actually quite old. Some my recommendation to update the Torch installation still stands.
