### ISSUE TITLE
Re Teacher Forcing

### ISSUE THREAD

**Issue by szubair-nara** [OpenNMT/OpenNMT#13]
This isn't necessarily an "issue" - but I was seeking clarity on whether this parameter enables teacher forcing:
"inputFeed - bool, enable input feeding"

**Comment by srush** [comment]
No they are different things. 

OpenNMT can only be trained with "teacher forcing", in that at training it uses the gold/reference input at each time step. Perhaps in the future we will add "data as demonstrator/scheduled sampling" style training. 

Input feeding refers to feeding the attention back into the network (say Luong's paper in the about section for details). This is quite helpful, and should generally be on.
