### ISSUE TITLE
break with translate server

### ISSUE THREAD

**Issue by anoidgit** [OpenNMT/OpenNMT#132]
I'm not sure about what changes have been done to the project, I just updated the package with git pull, but while I'm trying to start the `translation_server.lua`, it breaks with [`utils/Cuda.lua`](https://github.com/OpenNMT/OpenNMT/blob/master/onmt/utils/Cuda.lua#L47), I manually change it to `cutorch.manualSeedAll(opt.seed or 3435)`. I don't know whether I am the only one this problem happened to.

**Comment by anoidgit** [comment]
I think maybe we could make the `-seed` option into `utils/Cuda.lua`.

**Comment by anoidgit** [comment]
Another question, I have 1,200,000+ sentence pairs with a big dictionary which contains more than 1,000,000 phase pairs. If I want to get a good model for industry use, which options should I use? I'm training a model with 6 layers and 1000 rnn units per layer now, and I'm not sure whether I should use a bigger dropout rate or vocabulary size or not. I have much memory on GPU I could use, because of OpenNMT's efficient memory usage of course. Thank you if you could give me some advise.

**Comment by guillaumekln** [comment]
Thank you for reporting. The random seed was not properly initialized.

As for you question, let's keep it for the forum.

**Comment by anoidgit** [comment]
ok, Thank you. @guillaumekln
