### ISSUE TITLE
Could please help me check my simple Coverage Module?

### ISSUE THREAD

**Issue by anoidgit** [OpenNMT/OpenNMT#133]
I do not really know whether this is ok, to put a `onmt.Sequencer` in `nngraph` which will be encapsulated by another `onmt.Sequencer`. I think maybe I should to change `onmt.Sequencer` at the same time to prevent it clones `onmt.Sequencer` it contains.
This module is very different from the paper, I'm not sure whether it could improve the performance, but it is easy for me to write it.
I want to insert this module after the attention score was computed in `GlobalAttention.lua`([`attn = softmaxAttn(attn)`](https://github.com/OpenNMT/OpenNMT/blob/master/onmt/modules/GlobalAttention.lua#L48)).
Here is my current code, I'm still working on it.
```
require "nngraph"
local OddCoverage, parent = torch.class('onmt.OddCoverage', 'onmt.Sequencer')

function OddCoverage:__init(dim)
	parent.__init(self, self:_buildModel())
	self.step = 0
end

function OddCoverage:updateOutput(input)
	self.step = self.step + 1
	if self.step == 1 then
		self.cover, self.output = unpack(self:net(self.step):updateOutput({input.new():resizeAs(input):ones(), input}))
	else
		self.cover, self.output = unpack(self:net(self.step):updateOutput({self:net(self.step - 1).cover, input}))
	end
	return self.output
end

function OddCoverage:backward(input, gradOutput, scale)
	local gradCover, inputCover
	if self.step == #self.networkClones then
		gradCover = gradOutput.new():resizeAs(gradOutput):zero()
	else
		gradCover = self:net(self.step + 1).gradCover
	end
	if self.step ==1 then
		inputCover = input.new():resizeAs(input):ones()
	else
		inputCover = self:net(self.step - 1).cover
	end
	self.gradCover, self.gradInput = self:net(self.step):backward({inputCover, input}, {gradCover, gradOutput}, scale)
	self.step = self.step - 1
	return self.gradInput
end

--[[A OddCoverage module to reconstruct attention score(pay more attention to the part of context where it have not pay much attention to).
--]]
function OddCoverage:_buildModel()
	local old_cover = nn.Identity()()
	local attn = nn.Identity()()
	local cover_attn = nn.SoftMax()(nn.CMulTable()({old_cover, attn}))
	local new_cover = nn.ReLU()(nn.CSubTable()({old_cover, cover_attn}))
	return nn.gModule({old_cover, attn}, {new_cover, cover_attn})
end
```

**Comment by anoidgit** [comment]
It is hard for me to change the OpenNMT, because its modules' input and output are weird and difficult to understand for a new member, I hope someday Its code style could change like [`torch/nn`](https://github.com/torch/nn) which seems easier to modified.

**Comment by anoidgit** [comment]
I want to override function `clone()` of `onmt.Sequencer`, make it just return `self`, will it cause some problems?
```
function Sequencer:clone()
	return self
end
```

**Comment by guillaumekln** [comment]
The `Sequencer` is already cloning the whole graph so you usually don't want a submodule that clones itself. If I have some time, I will take a closer look at the feasibility of this particular module.

More generally, we are aware that the code is not the easiest to work with mostly because we need and want to support a lot of features within production constraints (for example, we chose to stick with `nngraph` for [CTranslate](https://github.com/OpenNMT/CTranslate)). However, we are planning to publish a light version of the model to ease the implementation of new ideas. Stay tuned for that!

**Comment by anoidgit** [comment]
I'm already running these code and waiting for the result. I'm glad to hear that and I will wait for your new publish.

**Comment by anoidgit** [comment]
I also add `nn.ReLU` to [`protectInput`](https://github.com/OpenNMT/OpenNMT/blob/master/onmt/utils/MemoryOptimizer.lua#L13) in `MemoryOptimizer.lua` to keep its input.

**Comment by wsnooker** [comment]
Hi, I am read to experiment with coverage model.
 
Was the attention or translation result better when added the simple coverage model in your experiments ?

**Comment by anoidgit** [comment]
Unfortunately no, I'm reading the original paper and trying to find out a new way. @wsnooker
