### ISSUE TITLE
Train error using GPU

### ISSUE THREAD

**Issue by wsnooker** [OpenNMT/OpenNMT#134]
I checkout the new version v0.4.1 and train the model using gpu , but occurring a error.

The logs as follows:

> root@1311868b778e:/home/ww110750/OpenNMT# th train.lua -config conf/train.conf -gpuid 1
> [02/19/17 04:37:00 INFO] Using GPU(s): 1
> [02/19/17 04:37:00 INFO] Loading data from 'data/demo-train.t7'...
> [02/19/17 04:37:01 INFO]  * vocabulary size: source = 24999; target = 35820
> [02/19/17 04:37:01 INFO]  * additional features: source = 0; target = 0 
> [02/19/17 04:37:01 INFO]  * maximum sequence length: source = 50; target = 51   
> [02/19/17 04:37:01 INFO]  * number of training sentences: 10000 
> [02/19/17 04:37:01 INFO]  * maximum batch size: 128
> [02/19/17 04:37:01 INFO] Building model...
> [02/19/17 04:37:05 INFO]  * using input feeding 
> [02/19/17 04:37:05 INFO] Initializing parameters...
> [02/19/17 04:37:08 INFO]  * number of parameters: 83281320
> [02/19/17 04:37:08 INFO] Preparing memory optimization...
> /root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/nn/THNN.lua:109: bad argument #3 to 'v' (cannot convert 'struct THLongTensor *' to 'struct THCudaTensor *')
> stack traceback:
>         [C]: in function 'v'
>         /root/torch/install/share/lua/5.1/nn/THNN.lua:109: in function 'ClassNLLCriterion_updateOutput'
>         /root/torch/install/share/lua/5.1/nn/ClassNLLCriterion.lua:41: in function 'updateOutput'
>         /root/torch/install/share/lua/5.1/nn/ParallelCriterion.lua:23: in function 'forward'
>         ./onmt/modules/Decoder.lua:342: in function 'backward'
>         ./onmt/utils/Memory.lua:38: in function 'optimize'
>         train.lua:201: in function 'closure'
>         ./onmt/utils/Parallel.lua:81: in function 'launch'
>         train.lua:184: in function 'trainModel'
>         train.lua:566: in function 'main'
>         train.lua:571: in main chunk
>         [C]: in function 'dofile'
>         /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
>         [C]: at 0x00406670
>

**Comment by hjpwhu** [comment]
Same to me.

**Comment by guillaumekln** [comment]
What Torch version are you using?

**Comment by wsnooker** [comment]
Using `th` command, shows the version is `Torch7`

**Comment by guillaumekln** [comment]
If you installed Torch with the [standard procedure](http://torch.ch/docs/getting-started.html), could you share the output of:

```
cd ~/torch
git rev-parse HEAD
```

You may have to update your Torch installation.

**Comment by wsnooker** [comment]
Type your command, and shows:

`5c578cf57d1d53a58eec5196ce5cdbc0f3abcb48`

**Comment by guillaumekln** [comment]
Did you manage to update your Torch installation and retry?

**Comment by wsnooker** [comment]
Update the torch and training works fine.

`cd torch;  sh ./update.sh`
