### ISSUE TITLE
Supporting different metrics?

### ISSUE THREAD

**Issue by hphong591992** [OpenNMT/OpenNMT#135]
In future, will you guys support some other metrics such as BLEU, CIDEr, ... ?

**Comment by guillaumekln** [comment]
Do you mean during the training or at translation time? In any case, I think we don't want to force any metrics as they are task-dependent.

**Comment by hphong591992** [comment]
It's for both. My point is it would be nice if OpenNMT has a feature where we can display multiple scores during both training and evaluation phases.

**Comment by vince62s** [comment]
@jsenellart-systran @guillaumekln I think also this is good point to think of when implementing the training scheduler. I did it when "simulating a scheduler within a bash script" where I calculate the Bleu score after each epoch.
Also there is a Moses script "analysis.perl" which scores each sentence of the test set and report useful information.
All of this is not really an"issue" but a better place would be "feature request" in the forum.
