### ISSUE TITLE
translate.lua:3: attempt to index field 'ExtendedCmdLine' (a nil value)

### ISSUE THREAD

**Issue by netxiao** [OpenNMT/OpenNMT#137]
I updated the package with git pull, when I use translate.lua got errors as below:
My env: Ubuntu 14.04 with Lua 5.2
> torch/install/bin/lua: translate.lua:3: attempt to index field 'ExtendedCmdLine' (a nil value)
> stack traceback:
>         translate.lua:3: in main chunk
>         [C]: in function 'dofile'
>         ...nNMT/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
>         [C]: in ?

**Comment by guillaumekln** [comment]
Can you check if the solution given in #117 works for you?

**Comment by netxiao** [comment]
it's ok now, many thanks! 
`luarocks remove opennmt`
`luarocks make rocks/opennmt-scm-1.rockspec`
ref:
https://github.com/OpenNMT/OpenNMT/issues/117#issuecomment-278649463
