### ISSUE TITLE
Maybe there are some memory on GPU could be freed while start the training?

### ISSUE THREAD

**Issue by anoidgit** [OpenNMT/OpenNMT#147]
I do not know why, but It need obviously less memory if I start the trainning with a checkpoint.

**Comment by guillaumekln** [comment]
How much difference do you experience?

**Comment by anoidgit** [comment]
I'm training a model with 8 layers and residue connection, It need 7000+M to build a new model and train it, but 6303M to train from a checkpoint. @guillaumekln

**Comment by guillaumekln** [comment]
Why is it closed? Did you solve it somehow?

**Comment by anoidgit** [comment]
I use part of the code to get another script which build a model and save it, then use `train.lua` to retrain the saved model. For small model, just train is ok, for big model, this two step will make the job done, and I do not think this is a big problem. @guillaumekln
