### ISSUE TITLE
How to print the types of Encoder in the model ?

### ISSUE THREAD

**Issue by wsnooker** [OpenNMT/OpenNMT#151]
I loaded the pretrained model, and want to know the types of the Encoder, as Encoder, BiEncoder.

How could I print the name of such configuration ?

**Comment by wsnooker** [comment]
I add the logs in `load(pretrained)` method in `Encoder.lua` and `BiEncoder.lua` class.

Run the translation scripy, and occur strange logs: 

> BiEncoder called
> UniEncoder called
> UniEncoder called

Why was the Encoder called twice ?  But the model was trained with `BiRnn` configuration.

**Comment by guillaumekln** [comment]
`brnn` is actually a combination of two `Encoder`s: one for the actual input and another for the reversed input.

**Comment by wsnooker** [comment]
hmm, I forgot this point.  Thank you
