### ISSUE TITLE
Embedding Convert not working

### ISSUE THREAD

**Issue by srush** [OpenNMT/OpenNMT#154]
embedding_convert is no more working with latest version of ONMT, because of the lack of this file:
onmt/utils/Opt.lua

Of course, it's still working with my previous old ONMT installation.
:stuck_out_tongue:

**Comment by guillaumekln** [comment]
#54 has still not been merged. So it is not really an issue but should be referenced in the PR itself.

**Comment by srush** [comment]
Oops thanks. (this was copied from a forum post.)
