### ISSUE TITLE
How can I trace better this error ?

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/OpenNMT#164]
[03/13/17 11:38:28 INFO] Building source vocabularies...	
[03/13/17 11:38:32 INFO] Created word dictionary of size 16836 (pruned from 16836)	
/home/moses/torch/install/bin/luajit: ./onmt/data/Vocabulary.lua:142: attempt to index a nil value
stack traceback:
	./onmt/data/Vocabulary.lua:142: in function 'init'
	tools/build_vocab.lua:26: in function 'main'
	tools/build_vocab.lua:34: in main chunk
	[C]: in function 'dofile'
	...oses/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670

**Comment by netxiao** [comment]
you may need to run:
```
luarocks remove opennmt
luarocks make rocks/opennmt-scm-1.rockspec
```

**Comment by vince62s** [comment]
it's actually a different problem with symlinks not using the good version.
