### ISSUE TITLE
Additional options for base model

### ISSUE THREAD

**Issue by shahbazsyed** [OpenNMT/OpenNMT#172]
The [about](http://opennmt.net/about/) section says there are options implemented for improving the base model. I want to how to use these options while training my model. More specifically, I would like to use local attention,guided alignment and fast forward connections. 

Any guidance is appreciated!

**Comment by guillaumekln** [comment]
I replied on the forum: http://forum.opennmt.net/t/where-are-the-additional-options-for-the-base-model/329
