### ISSUE TITLE
Huge difference in perplexity score from iteration to iteration

### ISSUE THREAD

**Issue by mdasadul** [OpenNMT/OpenNMT#181]
I am doing two test with the latest code in this repository on Ubuntu 16.04, CUDA-8.0 and I updated my torch last week

1.  With two GPUs and I am using demo data. It's working as expected. 
![correct_ppl](https://cloud.githubusercontent.com/assets/8009589/24629459/085a0a56-1887-11e7-90ce-6f499f7a57c5.PNG)
2. With four GPUs and with the same data The perplexity score is fluctuating too much. With my actual data it is doing that so I wanted to recreate the problem and I am sharing a screen shot
![wrong_ppl](https://cloud.githubusercontent.com/assets/8009589/24629637/b41c624e-1887-11e7-88f8-eb1dd6d0905e.PNG)

**Comment by guillaumekln** [comment]
As stated in the guide for asynchronous training:

> Note that a GPU core is dedicated to storage of the master copy of the parameters and is not used for training.

So in the first screenshot it is actually a training with a single GPU.

For the second screenshot, the asynchronous computation starts when:

```lua
epoch > 1 or iteration < opt.async_parallel_minbatch
```

with `-async_parallel_minbatch` defaulting to 1000. In you case, asynchronous computation starts at the beginning of epoch 2 after 649 batches of size 16 which may not be enough to provide a good initialization for asynchronous mode to converge.

With the size of your dataset, I would not use multiple GPUs at all.

**Comment by mdasadul** [comment]
I was using this with 20Million training sentences and yes after `iteration < opt.async_parallel_minbatch`  PPL is jumping from 4001.12 to 199928390.90 and again 54789032.65. Is it right behavior?

After `iteration < opt.async_parallel_minbatch` I also saw the number of source tokens/s increased from 1900 to 3500.

**Comment by guillaumekln** [comment]
Did the perplexity completely diverge or did it go down after some iterations?

**Comment by mdasadul** [comment]
I will say it is fluctuating too much. I waited 2/3 hours to go down but It did not happen. I will recreate the problem and possible share screen short but as I have only 4 GPUs and 2 of them are used, So i will wait few days to complete one epoch.

Thanks for your support though

**Comment by mdasadul** [comment]
Here is the screen shot perplexity odd jumping. It's even becoming NAN and I stop it. I am using same command as above except 4 GPUs
![incorrect_ppl](https://cloud.githubusercontent.com/assets/8009589/24671044/49de48a4-193e-11e7-94f1-58b4c00b8a6c.PNG)

**Comment by jsenellart-systran** [comment]
Hello @mdasadul - could you retry the same on a more recent version? the ppl fluctuation  for the first epochs when the async really starts is not that surprising, when the network is not really initialized the async convergence is a bit random since all the replica are fighting against each other to find the way down. as Guillaume stated, you can try to increase `async_parallel_minbatch` default value to unleash the replica only on a more stable nn.
but the `nan` is not normal so I welcome any reproduction scenario.

**Comment by mdasadul** [comment]
Thanks @jsenellart-systran for getting back to me. I am closing the issue for now and  I will reopen the issue if that problem still exists with more recent version of the code.

Thanks
