### ISSUE TITLE
problem with "Multi-GPU training"

### ISSUE THREAD

**Issue by nicolabertoldi** [OpenNMT/OpenNMT#183]
I tried to use OpenNMT on a Ubuntu machine with 4 GPUs,
but train fails, even if I used just one GPU (-gpuid 2), no matter which GPU I choose.

I do not experience problem using a 1-GPU machine.

My machine is a VM on Azure (Ubuntu 16.04) with CUDA 8.0.
The software and libraries were installed using a VM with  1 GPU;
and then switched off and restarted as a 4-GPUs machine.

Note that the command 'nvidia-smi' finds all 4 GPUs
$> nvidia-smi 
Tue Apr  4 12:38:19 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.39                 Driver Version: 375.39                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M60           Off  | 98CB:00:00.0     Off |                  Off |
| N/A   38C    P0    39W / 150W |      0MiB /  8123MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla M60           Off  | AE74:00:00.0     Off |                  Off |
| N/A   33C    P0    40W / 150W |      0MiB /  8123MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla M60           Off  | B269:00:00.0     Off |                  Off |
| N/A   42C    P0    40W / 150W |      0MiB /  8123MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla M60           Off  | B48D:00:00.0     Off |                  Off |
| N/A   35C    P0    39W / 150W |      0MiB /  8123MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

Here is the command I run for training
$> th /home/nmt_nicola/software/OpenNMT/train.lua -data my_data/corpus-train.t7 -save_model my_model/corpus-model -gpuid 2

And here an excerpt of the log
[04/04/17 12:28:42 INFO] Using GPU(s): 2	
........
........
[04/04/17 12:28:57 INFO] Initializing parameters...	
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-1949/cutorch/lib/THC/generic/THCTensorMath.cu line=35 error=8 : invalid device function
/home/nmt_nicola/software/torch/install/bin/luajit: ./onmt/modules/WordEmbedding.lua:32: cuda runtime error (8) : invalid device function at /tmp/luarocks_cutorch-scm-1-1949/cutorch/lib/THC/generic/THCTensorMath.cu:35
stack traceback:
	[C]: in function 'zero'
	./onmt/modules/WordEmbedding.lua:32: in function 'postParametersInitialization'
	./onmt/Model.lua:67: in function 'callback'
	...icola/software/torch/install/share/lua/5.1/nn/Module.lua:352: in function 'apply'
	...icola/software/torch/install/share/lua/5.1/nn/Module.lua:356: in function 'apply'
	...icola/software/torch/install/share/lua/5.1/nn/Module.lua:356: in function 'apply'
	./onmt/Model.lua:65: in function 'initParams'
	./onmt/train/Trainer.lua:67: in function 'closure'
	./onmt/utils/Parallel.lua:79: in function 'launch'
	./onmt/train/Trainer.lua:62: in function 'train'
	/home/nmt_nicola/software/OpenNMT/train.lua:129: in function 'main'
	/home/nmt_nicola/software/OpenNMT/train.lua:134: in main chunk
	[C]: in function 'dofile'
	...ware/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

**Comment by guillaumekln** [comment]
This seems like an installation issue and the consequences of:

> The software and libraries were installed using a VM with 1 GPU; and then switched off and restarted as a 4-GPUs machine.

are unclear.

 I would start by reinstalling Torch.

**Comment by nicolabertoldi** [comment]
I reinstalled Torch on the 4-GPU machine
and OpenNMT training works properly.

But If i switch off the machine, restart it as 1-GPU instance, and retry training I got the same error

THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-8591/cutorch/lib/THC/generic/THCTensorMath.cu line=35 error=8 : invalid device function
/home/nmt_nicola/software/torch/install/bin/luajit: ./onmt/modules/WordEmbedding.lua:32: cuda runtime error (8) : invalid device function at /tmp/luarocks_cutorch-scm-1-8591/cutorch/lib/THC/generic/THCTensorMath.cu:35



Hence, I would claim that the installation of Torch is dependent on the amount of GPUs, and it is not "portable"

Is there any intrinsic reason for this?

**Comment by guillaumekln** [comment]
Yes, I would not expect the Torch installation to be portable as it compiles from sources and (certainly) detect available hardware.
