### ISSUE TITLE
choice of GPUs

### ISSUE THREAD

**Issue by nicolabertoldi** [OpenNMT/OpenNMT#184]
I am using OpenNMT on a 4-gpu machine.

I am running the training with this setting '-gpuid 1'
but the GPU actually used is the 3as shown by "nvidia-smi'

$> nvidia-smi 
Tue Apr  4 15:19:06 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.39                 Driver Version: 375.39                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M60           Off  | 8469:00:00.0     Off |                  Off |
| N/A   59C    P8    16W / 150W |      2MiB /  8123MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla M60           Off  | A740:00:00.0     Off |                  Off |
| N/A   35C    P8    14W / 150W |      2MiB /  8123MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla M60           Off  | A7BC:00:00.0     Off |                  Off |
| N/A   31C    P8    14W / 150W |      2MiB /  8123MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla M60           Off  | AD6B:00:00.0     Off |                  Off |
| N/A   76C    P0   100W / 150W |   3006MiB /  8123MiB |     97%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    3      2545    C   .../torch/install/bin/luajit  3004MiB |
+-----------------------------------------------------------------------------+

This appears to contradict the documentation
"For example:
       th train.lua -data data/demo-train.t7 -save_model demo -gpuid 1,2,4
will use the first, the second and the fourth GPU of the machine."

What does the number specified with gpuid exactly refer to?
And why does it not start from 0?

**Comment by guillaumekln** [comment]
Maybe we should be more precise. They are "the first, the second and the fourth GPU of the machine" as returned by the CUDA API and not the driver API as used by `nvidia-smi`. Both IDs can be different.

It is 1-indexed because Lua is 1-indexed.

**Comment by nicolabertoldi** [comment]
thanks for the clarification
