### ISSUE TITLE
output oov words

### ISSUE THREAD

**Issue by anglil** [OpenNMT/OpenNMT#202]
Hi OpenNMT, is there a way to output a list of out-of-vocabulary (OOV) words when translating/testing/decoding?
Thanks!

**Comment by guillaumekln** [comment]
Hi,

There is no built-in tool or option for that. However, the preprocessing step generated `.dict` files containing the word vocabulary. You could write a simple script that iterates on your data and outputs every words that are not in the `.dict` file.

**Comment by anglil** [comment]
Thanks! Does the dict store lower-cased words or the original words as in the training data?

**Comment by guillaumekln** [comment]
The original words as in the training data.

**Comment by anglil** [comment]
Thanks!

**Comment by anglil** [comment]
How does the example code handle OOV words? It seems that the translation doesn't have any OOV words at all. Thanks.

**Comment by guillaumekln** [comment]
What do you mean by "example code"?

**Comment by anglil** [comment]
By that I mean the code presented in http://opennmt.net/OpenNMT/quickstart/
When encountering an OOV word in translating, does translate.lua choose a word from the vocabulary established in the preprocessing phrase for translation? Thanks!

**Comment by guillaumekln** [comment]
Yes translate.lua uses the vocabulary generated by the preprocessing.

All OOV words are mapped to a single `<unk>` token. For more details at translation time, see http://opennmt.net/OpenNMT/translation/unknowns/.

**Comment by anglil** [comment]
OK. Thanks.
