### ISSUE TITLE
{"error":"tools/translation_server.lua:47: attempt to index field 'opt' (a nil value)"}

### ISSUE THREAD

**Issue by netxiao** [OpenNMT/OpenNMT#215]
old code worked for me.

I used git pull && luarocks remove opennmt && luarocks make rocks/opennmt-scm-1.rockspec to update openNMT.

When I send string to server by zmq_requester, I got error:

`{"error":"tools/translation_server.lua:47: attempt to index field 'opt' (a nil value)"}`

**Comment by guillaumekln** [comment]
Thank you for reporting.
