### ISSUE TITLE
{"error":"...chBeamSearcher.lua:46: assertion failed!"}

### ISSUE THREAD

**Issue by netxiao** [OpenNMT/OpenNMT#219]
old version worked for me.
if -beam_size 5, worked, if set -beam_size <5 , report error.

I'm runing translation_server.lua:
```
th tools/translation_server.lua -beam_size **3** -host 0.0.0.0  -port 9999  -model model_it.t7  -replace_unk -phrase_table pb.txt  -log_level INFO
```

**Comment by guillaumekln** [comment]
Is it your actual command line? Do you have local modifications?

**Comment by netxiao** [comment]
it is script:
 th tools/translation_server.lua -beam_size 5 -host 0.0.0.0  -port 9999  -n_best 5 -length_norm 0 -coverage_norm
 1 -eos_norm 0  -model model_it.t7  -replace_unk -phrase_table pb.txt  -log_level INFO

**Comment by guillaumekln** [comment]
You can't request a list of the 5-best hypotheses with a beam of size 3.

**Comment by netxiao** [comment]
I know, many thanks!
