### ISSUE TITLE
Training sequence labeling model

### ISSUE THREAD

**Issue by pshashk** [OpenNMT/OpenNMT#220]
I've preprocessed the data as `monotext` with one feature. When I try to train `seqtagger` type model I get the following error:

```
./onmt/Factory.lua:143: attempt to concatenate field 'dropout' (a nil value)
```
What am I doing wrong?

**Comment by guillaumekln** [comment]
Thanks for reporting, there was a small error in the code.

Also, for sequence tagging you should preprocess your data with `bitext`. The target file is one space-separated sequence of tags per line.
