### ISSUE TITLE
FATAL THREAD PANIC: (write) not enough memory

### ISSUE THREAD

**Issue by wolfshow** [OpenNMT/OpenNMT#222]
when I use 4 GPUs for parallel training. I got this error information. Does anyone have the same problem?

**Comment by shahbazsyed** [comment]
Hi @wolfshow ,
Do you have an error which says ```module threads.queue not found```  ? Because this was the case for me .
You can try updating to Lua5.2 , reinstalling cutorch, cunn, as this resolved the issue for me. 

You may want to post the complete error / screen shot to help anyone identify your problem.

**Comment by guillaumekln** [comment]
Closing this one.

Using Lua 5.2 should fix this.
