### ISSUE TITLE
data preprocessing / special cases management

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/OpenNMT#223]
A few weeks ago, @guillaumekln fixed an issue where you can potentially have in parallel data, one side with an empty line with the other side being non-empty.
Not sure but I think we decided to eliminate these lines.

I am having the same issue with Index / vectors files.
My idx vector file (MFCC is sometimes not empty eg a short silence) and there is no corresponding key indexed text on the target side because no transcription.

I could adjust my dataset but this is tha way they are dumped from Kaldi.

Hope this is clear.

At the moment preprocessor.lua dies with an error when encountering this case, but there is a little bit more to do I think.

EDIT: parallelizing this preprocess would be good too...:)

**Comment by jsenellart-systran** [comment]
Hi @vince62s - just to double check: what you would like is when using `idx_files`, we can have in some case some entry in source and missing target entry in target - and you want in that case to skip them, right?

**Comment by vince62s** [comment]
yes absolutely.
We fixed that same scenario with bitext with Guillaume.
