### ISSUE TITLE
restserver.lua:113: attempt to concatenate local 'err' (a nil value)

### ISSUE THREAD

**Issue by netxiao** [OpenNMT/OpenNMT#225]
rest Server script:
`th tools/rest_translation_server.lua -port 8888 -model model_it.t7  -replace_unk -phrase_table pb.txt  -log_level INFO `
client script:
`curl -v -H "Content-Type: application/json" -X POST -d '[{ "src" : "Hello World }]' http://127.0.0.1:8888/translator/translate`
error msg:

> * Hostname was NOT found in DNS cache
> *   Trying 127.0.0.1...
> * Connected to 127.0.0.1 (127.0.0.1) port 8888 (#0)
> > POST /translator/translate HTTP/1.1
> > User-Agent: curl/7.35.0
> > Host: 127.0.0.1:8888
> > Accept: */*
> > Content-Type: application/json
> > Content-Length: 26
> > 
> * upload completely sent off: 26 out of 26 bytes
> < HTTP/1.1 500
> < Date: Mon, 24 Apr 2017 07:07:24 GMT
> < Content-Length: 935
> < Content-Type: text/html
> * Server SGA is not blacklisted
> < Server: SGA
> < 
>         <html>
>         <head><title>WSAPI Error in Application</title></head>
>         <body>
>         <p>There was an error in the specified application.
>         The full error message follows:</p>
> <pre>
> /yfsys/work/torch/install/share/lua/5.2/restserver.lua:113: attempt to concatenate local 'err' (a nil value)
> stack traceback:
>         /yfsys/work/torch/install/share/lua/5.2/restserver.lua:113: in function </yfsys/work/torch/install/share/lua/5.2/restserver.lua:93>
>         (...tail calls...)
>         [C]: in function 'xpcall'
>         /yfsys/work/torch/install/share/lua/5.2/wsapi/common.lua:270: in function 'run_app'
>         /yfsys/work/torch/install/share/lua/5.2/wsapi/xavante.lua:89: in function </yfsys/work/torch/install/share/lua/5.2/wsapi/xavante.lua:49>
>         (...tail calls...)
>         /yfsys/work/torch/install/share/lua/5.2/xavante/httpd.lua:64: in function </yfsys/work/torch/install/share/lua/5.2/xavante/httpd.lua:42>
> </pre>
>         </body>
>         </html>
> * Connection #0 to host 127.0.0.1 left intact

**Comment by guillaumekln** [comment]
There was missing end quote in the command example. It is:

```
'[{ "src" : "Hello World" }]'
```

not:

```
'[{ "src" : "Hello World }]'
```
