### ISSUE TITLE
Encoding of translated text

### ISSUE THREAD

**Issue by raju249** [OpenNMT/OpenNMT#230]
Hi team,

I am using openNMT for English-Hindi translation.
I have the corpus and trained model out of it, but when I translate, the output is not properly encoded.
It appears to be distorted.

Here is the example of that:
```कन े क ् शन क ी पह ु ँ च य ो ग ् य स ा मग ् र ी क ी स ् वत ः प ू र ् ण ह ै ```

Is this has to do something with utf-8 encoding ?

Thanks for your help.

**Comment by guillaumekln** [comment]
Hi,

What do you mean by "distorted"? It seems like an actual Hindi sentence.

**Comment by raju249** [comment]
No,
See the dotted circles, they should not be there.
The dotted circles actually break a single letter in two.

**Comment by guillaumekln** [comment]
It seems your training data contains such characters.

Could you check your target file and the generated dictionary (with the `.tgt.dict` suffix) for such characters?

**Comment by raju249** [comment]
```
लिपि प्रकार
लिपि रेकोर्डर
श्वानपुच्छ शैली की लिपियां निर्मित करता है
वर्तमान लिपि (स्क्रिप्ट) खो जाएगी।
मिटाने की पुष्टि करें
स्कीमा:
सत्यापन
खाली
कोई विवरण नहीं
एटी-एसपीआई सत्यापक
अनुप्रयोग की पहुंचनीयता का सत्यापन करता है
फोकस योग्य %s में सारणी अंतराफलक है, कोई चयनीय अंतराफलक नहीं हैbutton has focused state without focusable state
एक्सेर्साइसर सर्वाधिकार © 2006, 2007 आईबीएम निगम (बीएसडी)
प्लग-इन त्रुटियां
संपादित करें
...
```

This is the training data @guillaumekln 

All the tokens, dict is generated using this data

**Comment by raju249** [comment]
@guillaumekln Any update ?
Thanks for your time ?

**Comment by guillaumekln** [comment]
I don't see any encoding issue as all characters are correctly formatted.

I think you should check your training corpus as the model only outputs what it learned from the data.

**Comment by raju249** [comment]
Ok.
May be some issue with fonts in the vi editor ?
Which might create problem.
What you think ?

**Comment by raju249** [comment]
Hi @guillaumekln 
The training data is the above that I mentioned in the thread.

The problem is in the token file that is generated when the tokenize the corpus.

Check the content
```
ल ि प ि प ् रक ा र
ल ि प ि र े क ो र ् डर
श ् व ा नप ु च ् छ श ै ल ी क ी ल ि प ि य ा ं न ि र ् म ि त करत ा ह ै
वर ् तम ा न ल ि प ि ( स ् क ् र ि प ् ट ) ख ो ज ा एग ी ।
म ि ट ा न े क ी प ु ष ् ट ि कर े ं
स ् क ी म ा :
सत ् य ा पन
ख ा ल ी
क ो ई व ि वरण नह ी ं
एट ी - एसप ी आई सत ् य ा पक
अन ु प ् रय ो ग क ी पह ु ं चन ी यत ा क ा सत ् य ा पन करत ा ह ै
फ ो कस य ो ग ् य % s म े ं स ा रण ी अ ं तर ा फलक ह ै , क ो ई चयन ी य अ ं तर ा फलक नह ी ं ह ै button has focused state without focusable state
एक ् स े र ् स ा इसर सर ् व ा ध ि क ा र © 2006 , 2007 आईब ी एम न ि गम ( ब ी एसड ी )
प ् लग-इन त ् र ु ट ि य ा ं
स ं प ा द ि त कर े ं
प ु स ् तक-च ि ह ् न स ं प ा द ि त कर े ं ( _E ) . . .
क ु ं ज ी ब ं धन
व ि षय प ् रक ा र
न ि चल े पटल क े ल ि ए ड ि फ ो ल ् ट प ् लग-इन ख ा
```

I think this where its coming from.
What you think ?

**Comment by raju249** [comment]
I think this has got to do something with ```tokenize.lua```  file.

**Comment by guillaumekln** [comment]
@jsenellart-systran An idea here?

**Comment by jsenellart-systran** [comment]
Yes - we are missing DEVANAGARI characters in unicode table - I am taking the point. @raju249 - thanks for reporting.

**Comment by raju249** [comment]
Thanks @guillaumekln and @jsenellart-systran 
So just to speed up things in my project, how do I go about adding the chars in the table.
I found the file, wanted an insight on how to implement it.

Or should I wait for the next PR to be merged with this update ?

**Comment by jsenellart-systran** [comment]
the table is generated - it is a bit complicated. I should be done by tomorrow with this point.

**Comment by raju249** [comment]
Awesome @jsenellart-systran 
Thanks a lot 😄

**Comment by jsenellart-systran** [comment]
Hi @raju249 - I fixed the problem. Can you please validate that this is working as you want? I am not reading Hindi well 😉 ...

**Comment by raju249** [comment]
Checking it now @jsenellart-systran 😄

**Comment by raju249** [comment]
@jsenellart-systran It worked! 👍 
Thanks for your fix 😃
