### ISSUE TITLE
Bridge.lua:56: attempt to call field 'MapTable' (a nil value)

### ISSUE THREAD

**Issue by netxiao** [OpenNMT/OpenNMT#232]
when I upgraded to last source code and run rest_translation_server.lua got errors:
my script:
`th tools/rest_translation_server.lua -beam_size 5  -n_best 5 -batch_size 64   -port 9999   -length_norm 0 -coverage_norm 1 -eos_norm 0  -model model_it.t7  -replace_unk -phrase_table pb.txt  -log_level INFO`

> lua: …/torch/install/share/lua/5.2/onmt/modules/Bridge.lua:56: attempt to call field 'MapTable' (a nil value)
> stack traceback:
> 	.../torch/install/share/lua/5.2/onmt/modules/Bridge.lua:56: in function 'load'
> 	/torch/install/share/lua/5.2/onmt/Seq2Seq.lua:146: in function 'load'
> 	...orch/install/share/lua/5.2/onmt/translate/Translator.lua:87: in function '__init'
> 	/torch/install/share/lua/5.2/torch/init.lua:91: in function 'new'
> 	tools/rest_translation_server.lua:142: in function 'main'
> 	tools/rest_translation_server.lua:149: in main chunk
> 	[C]: in function 'dofile'
> 	...work/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
> 	[C]: in ?

**Comment by guillaumekln** [comment]
What is your Torch version?

**Comment by netxiao** [comment]
lua5.2

**Comment by guillaumekln** [comment]
That is the Lua version. Could you go in your Torch directory and share the output of:

```
git rev-parse HEAD
```

**Comment by netxiao** [comment]
output:
`62ce9871a42c46893d3614827e56d3b27e992323`

**Comment by guillaumekln** [comment]
You should mention that you are not using an official Torch installation (https://github.com/intel/torch/tree/62ce9871a42c46893d3614827e56d3b27e992323).

You need at least to update the `nn` package to a more recent version.

**Comment by netxiao** [comment]
thanks
