### ISSUE TITLE
Indic language models

### ISSUE THREAD

**Issue by sridhar-newsdistill** [OpenNMT/OpenNMT#233]
if possible please include indian language models

**Comment by guillaumekln** [comment]
Currently, language modeling is an experimental feature to pre-initialize the encoder and/or decoder. They are not usable as is.

**Comment by sridhar-newsdistill** [comment]
what kind of support required to on board traslation for indian languages

**Comment by raju249** [comment]
I am trying the same.
I have training data eng-hindi parallel corpus, trained a model, but the text encoding is a problem that I am solving now.

**Comment by guillaumekln** [comment]
@sridhar-newsdistill I'm unsure what your request is. If you are looking for pretrained translation models with Hindi on the source or target, there is none at the moment. However, you can gather the data and train your own.

**Comment by sridhar-newsdistill** [comment]
Thanks  @guillaumekln
