### ISSUE TITLE
Out of memory when changing sequence length

### ISSUE THREAD

**Issue by shahbazsyed** [OpenNMT/OpenNMT#244]
Hi,
I changed my source and target sequence length options for the preprocess.lua config and set them to 300.
I also set the vocab size to 0 in order to have the complete vocabulary, as my dataset is really small (~75K pairs). When I run the train.lua with 4 gpus, I get out of memory errors even for such a small dataset.

![image](https://cloud.githubusercontent.com/assets/4356098/25563190/eb34fdd0-2d96-11e7-926c-4f3360038c7e.png)

Am  I doing something wrong here? I am using Lua 5.2 , CUDA 8.0, with max_batch_size = 16 and have also tried with THC_CACHING_ALLOCATOR = 0 appended to my cmdline , but to no success.

Kindly let me know If I need to change anything else.

**Comment by guillaumekln** [comment]
Hi,

Can you share the content of your configuration file? It seems the OOM is related to `JoinReplicateTable`.

Also note that GPU memory usage is not dependent on the dataset size and with such small dataset I would not use multiple GPUs for maximum efficiency.

**Comment by shahbazsyed** [comment]
Hi @guillaumekln 
These are the configurations i used 

preprocess.lua configuration file
`src_seq_length = 300
tgt_seq_length = 300
src_vocab_size = 0
tgt_vocab_size = 0
`

train.lua configuration file

`rnn_size = 600
layers = 2
brnn = true
global_attention = concat
optim = adam
learning_rate = 0.0002
`

**Comment by guillaumekln** [comment]
I'm not surprised it runs out of memory with such long sequences and large vocabulary. You should reduce these values first to fit on your GPU memory.

**Comment by shahbazsyed** [comment]
I have a few questions : 

Does the creation of the word embedding matrix(with the large vocabulary) happen only on a single GPU and not shared among GPUs?

Does using residual connections help for representing longer sequences?

**Comment by guillaumekln** [comment]
1. All GPUs have a full replica of the network and its parameters, including word embeddings.
2. Residual connections are vertical and mostly help for very deep encoders and decoders (> 4 layers)

**Comment by shahbazsyed** [comment]
Okay thanks. I will post further questions if any on the forum
