### ISSUE TITLE
Possible issue with counting length of sentences

### ISSUE THREAD

**Issue by hphong591992** [OpenNMT/OpenNMT#246]
I ran a word segmentation tool on English-Vietnamese dataset (~130k pairs of sentences). Here's the potential issue:
Before running the dataset, there was no sentences ignored by the pre-processor.
After running the segmentation tool, there were like 10% of the dataset were ignored by the pre-processor program.

What the segmentation tool only did is put underscore between words to combine them. (i.e X Y will become X_Y).

**Comment by guillaumekln** [comment]
Is it a segmentation tool you wrote?

With the information given, the issue is difficult to reproduce.

**Comment by hphong591992** [comment]
Ah, you're right. It was the issue of the segmentation. I used an open-source segmentation tool that has some bugs with it.
