### ISSUE TITLE
multi-gpu training not working?

### ISSUE THREAD

**Issue by michaelhutt** [OpenNMT/OpenNMT#248]
I'm having an issue training using multiple GPUs.

Using the process from the README.md:
`th preprocess.lua -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo`

`th train.lua -data data/demo-train.t7 -save_model model -gpuid 1 2`

I get an error in NCCL:
> ..../nccl/init.lua:52: attempt to call method 'getDevice' (a nil value)

(which is called from onmt/utils/Parallel.lua:111)

Debugging indicates that the type of the tensor passed to NCCL is a `torch.DoubleTensor`, rather than the expected `torch.Cuda*Tensor`.
 
Doing a `git bisect` seems to indicate that commit 8c5f97a is to blame.

**Comment by guillaumekln** [comment]
Thanks for reporting. Should be fixed with the commit above.
