### ISSUE TITLE
All words must have the same number of Features

### ISSUE THREAD

**Issue by mdasadul** [OpenNMT/OpenNMT#25]
I am trying to perform preprocessing  with different data than the demo and ended up getting following errors 

/usr/bin/luajit: ./onmt/utils/Features.lua:17: all words must have the same number of features
stack traceback:
        [C]: in function 'assert'
        ./onmt/utils/Features.lua:17: in function 'extract'
        preprocess.lua:56: in function 'makeVocabulary'
        preprocess.lua:122: in function 'initVocabulary'
        preprocess.lua:266: in function 'main'
        preprocess.lua:301: in main chunk
        [C]: in function 'dofile'
        /usr/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

Also I am wondering is there will be any preprocessor-shards.py here as data size grows few GB fitting them into memory will not be possible if we use preprocessing.py?

**Comment by guillaumekln** [comment]
What are the word features you are using? It seems that a word does not have the same number of annotations than others.

If you used the `tools/tokenize.lua` script with the case generation, can you locate the sentence that triggers this error and share it?

---

As for the shards support, how many sentences do you have and how much memory? The new preprocessing is more memory efficient than the one from seq2seq-attn. Let us know if it is still not enough for you.

**Comment by mdasadul** [comment]
This is the line which is responsible for the error
\right\|_0}$ is the number of nonzeroelements.

I am planning to train with 20M sentences  and I think this will be difficult to fit into 8GB GPU without using shards

**Comment by guillaumekln** [comment]
What is the tokenization you are using?

---

The whole dataset is never stored on the GPU. So it is limited by the CPU memory, not the GPU.

**Comment by mdasadul** [comment]
I am using the default tokenizer of OpenNMT. I am using following commands 
 th preprocess.lua -train_src ../data/src-train.txt -train_tgt ../data/targ-train.txt -valid_src ../data/src-validation.txt -valid_tgt ../data/targ-validation.txt -save_data data/train_data

**Comment by guillaumekln** [comment]
Can you retry with the latest version?

**Comment by mdasadul** [comment]
I recreate the same error with this sentence by latest version 
Consider the linear space $\mathbb{R}$ endowed with the scalar product $\langle\cdot, \cdot\rangle$ and the associated norm $\|x\|$.

**Comment by guillaumekln** [comment]
May I ask the exact command line you run to tokenize your data?

**Comment by mdasadul** [comment]
th preprocess.lua -train_src ../data/src-train.txt -train_tgt ../data/targ-train.txt -valid_src ../data/src-validation.txt -valid_tgt ../data/targ-validation.txt -save_data data/train_data

**Comment by guillaumekln** [comment]
This the command line of the preprocessing. You said you are using the OpenNMT tokenizer on your data. How do you run `tools/tokenize.lua`?

**Comment by mdasadul** [comment]
Well I am not running tools/tokenize.lua but I think preprocess.lua is using it

**Comment by jsenellart-systran** [comment]
preprocess.lua is assuming the corpus is tokenized. 
please check https://github.com/OpenNMT/OpenNMT/tree/master/tools for how to use tokenizer.lua

**Comment by srush** [comment]
Can we add an enhancement to have different numbers of features on the encoder side with the "sum" combiner? For instance this could be useful for implementing the subword character ngram features.

**Comment by guillaumekln** [comment]
Closing this one.

The original issue is no more relevant as we changed the way to separate features of few days after the issue was originally reported.

The feature request is tracked on the forum: http://forum.opennmt.net/t/variable-size-features/25
