### ISSUE TITLE
Very high perplexity values

### ISSUE THREAD

**Issue by shahbazsyed** [OpenNMT/OpenNMT#265]
Hi,
I am training 530K sequences of length less than 200 words, english -> english . My training configuration is
`layers = 4
 rnn_type = GRU
 rnn_size = 600
 max_batch_size = 10
 residual = true
 brnn = true
 brnn_merge = concat
 global_attention = concat
 end_epoch = 30
`

I am getting really high perplexity values in the first epoch : 
![image](https://cloud.githubusercontent.com/assets/4356098/25773697/4a64fca2-3282-11e7-873c-0afef474bc00.png)

Is this normal? Or am I doing something wrong here?

**Comment by guillaumekln** [comment]
Could you try with a lower learning rate (e.g. 0.1)?

If that does not help, you should then try without `global_attention = concat` as this layer is somewhat new and not extensively tested.

**Comment by beichao1314** [comment]
I have met the same problem when I use GRU with the SGD.
You can try the Adam and small learning rate with GRU. It may be OK.

**Comment by shahbazsyed** [comment]
@beichao1314 , @guillaumekln 
Thanks for the suggestions! I am running it with a learning rate of 0.1 and SGD with GRU. It seems to work fine. I shall let you know the quality of the results once done.

@beichao1314 I tried using Adam with a smaller dataset, and faced some issues with very slow iterations in the epochs. After a few epochs, the program just crashed with out of memory exceptions. I wonder why this happened only when using Adam and not SGD on the same dataset. It would be nice if you can give me some insights into the relation between the optimization methods and memory usage (if any at all ).

**Comment by beichao1314** [comment]
Sorry, I always use sgd and lstm, using GRU with Adam is just in test. So, I have nothing to suggest.
