### ISSUE TITLE
Different results obtained with/without "-disable_mem_optimization" option

### ISSUE THREAD

**Issue by frankang** [OpenNMT/OpenNMT#266]
Hi,
I trained the model with and without the `-disable_mem_optimization` option, but got different results. Could someone tell me which result should I trust? Thanks!

I'm using the train data provided within the repository. And below is the code I ran.
`th preprocess.lua -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo` 

`th train.lua -data data/demo-train.t7 -save_model model -gpuid 2 -disable_mem_optimization`
result: Saving checkpoint to 'model_epoch13_960.68.t7'

`th train.lua -data data/demo-train.t7 -save_model model -gpuid 2`
result: Saving checkpoint to 'model_epoch13_781.85.t7'...

**Comment by guillaumekln** [comment]
Hi,

Both results are valid and the effect of randomness during the training.

More precisely, the state of the random number generator is the same in both cases but memory optimization requires an initial forward and backward pass that uses this generator with the dropout.

**Comment by frankang** [comment]
Thanks for the clarification, I'll close the issue.
