### ISSUE TITLE
breaking change ?

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/OpenNMT#267]
Hi,
On a production server (not updated with very recent version), it works fine without -case_feature
but if I use -case_feature with a new model (recent version onmt) but run on the "old" production server, I get this error
/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <onmt.Bridge>

the bridge copy stuff is breaking ?

**Comment by guillaumekln** [comment]
Hi,

We don't support forward compatibilty and using models trained in the future. Unless otherwise noted, a model trained with version X can only be used with version Y >= X.
