### ISSUE TITLE
Could this library support modules in Element-Research/rnn?

### ISSUE THREAD

**Issue by anoidgit** [OpenNMT/OpenNMT#28]
I am familiar with Element-Research/rnn, and I do not know how encoder and decoder work, so I hope I could build a module with Element-Research/rnn to initialize the rnn of encoder and decoder.

**Comment by anoidgit** [comment]
In another word, I hope I could give a rnn like nn.LSTM/nn.GRU/nn.Sequential():add(nn.GRU):add(nn.LSTM) of Element-Research/rnn to encoder and decoder.

**Comment by srush** [comment]
Unfortunately opennmt is not compatible with elementrnn. We were inspired by their design, but we needed to give up some flexibility for more fine grain control for memory and performance. 

However you should not need to "give" an rnn to our library, it had it's own internal lstm. If you want to build a different external architecture you can use our components.

**Comment by anoidgit** [comment]
Thank you for your answer, I want to use something like norm-stabilization implement by element rnn, and maybe I could try to fit your design. @srush

**Comment by srush** [comment]
We would love a pull request :)
