### ISSUE TITLE
unknown torch class <tds.Vec>

### ISSUE THREAD

**Issue by bluebear94** [OpenNMT/OpenNMT#280]
When I try to test-translate using a model, I get the following error message:

```
$ th translate.lua -model mydata/demo-train.t7 -src mydata/src-test.txt -output mydata/pred.txt
[05/19/17 19:45:50 INFO] Loading 'mydata/demo-train.t7'...	
/home/uruwi/torch/install/bin/luajit: /home/uruwi/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <tds.Vec>
stack traceback:
	[C]: in function 'error'
	/home/uruwi/torch/install/share/lua/5.1/torch/File.lua:343: in function 'readObject'
	/home/uruwi/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/uruwi/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/uruwi/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/uruwi/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	./onmt/translate/Translator.lua:117: in function '__init'
	/home/uruwi/torch/install/share/lua/5.1/torch/init.lua:91: in function 'new'
	translate.lua:53: in function 'main'
	translate.lua:196: in main chunk
	[C]: in function 'dofile'
	...ruwi/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x5619de3af470
```

This might be an issue with Torch itself rather than OpenNMT.

**Comment by guillaumekln** [comment]
It seems you did not provide a trained model but the data package prepared during the preprocessing step.

**Comment by bluebear94** [comment]
Can translate.lua at least recognise the error and tell the user what's wrong?

**Comment by guillaumekln** [comment]
Yes it could. We already check many user options, it is hard to cover every possible mistakes though.

**Comment by asonipsl** [comment]
This might be late response... but when I looked in to your command:
    th translate.lua -model mydata/demo-train.t7 -src mydata/src-test.txt -output mydata/pred.txt
It is clear that you are providing preprocessed training data (mydata/demo-train.t7) as argument instead of saved model. The argument for option "-model" must be a valid saved model which is normally stored as "<userProvidedSuffix>_epoch<Count>.<digit>.<digit>.t7" for example model_epoch13_5.39.t7
