### ISSUE TITLE
poor results pdbrnn

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/OpenNMT#281]
if someone could confirm my results with pdbrnn, it would be good.
I tested on baseline 1M en-fr.
2x500 reduction 2
2x1000 reduction 2
2x300 reduction 2

All of them give very poor results. PPL above 8 or 9 after 13 epochs, BLEU scores are ridiculous.

In my view 2x1000 should be at least as good as 2x500 dbrnn.

Cheers.

**Comment by guillaumekln** [comment]
Could you try translating with `-batch_size 1` and report how the BLEU score differs?

**Comment by vince62s** [comment]
almost no change, from 3 to 5 ....
the issue starts with the PPL anyway, no ?

**Comment by jsenellart-systran** [comment]
just to clarify, the pyramidal reduction is on time, not on the context size - so 2x1000 reduced can not be compared to 2x500 without reduction. to compare we need to prepare a corpus where each word is doubled. I will prepare some validation dataset for this feature.

**Comment by vince62s** [comment]
okay, so what we are saying, with 2 layer and reduction of 2, is : we train a corpus with bi-grams in input and 1-gram in output, Am I correct ?

**Comment by jsenellart-systran** [comment]
ok I reproduce the same on text - I took 100k baseline EN>FR corpus. After tokenization, I double each word in source and compare:

* dbrnn on original corpus => ends with ppl ~6
* pdbrnn (2 layer, reduction 2) on double src corpus => ends with ppl ~20

We would expect almost the same ppl

**Comment by vince62s** [comment]
closing this, see https://github.com/OpenNMT/OpenNMT/pull/295
