### ISSUE TITLE
ImportError: No module named sugartensor

### ISSUE THREAD

**Issue by ljy296566** [OpenNMT/OpenNMT#283]
I install `sugartensor` by using
`sudo pip install sugartensor`
and success
`Collecting sugartensor
  Downloading sugartensor-1.0.0.2.tar.gz
Collecting tqdm>=4.8.4 (from sugartensor)
  Downloading tqdm-4.11.2-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 616kB/s 
Installing collected packages: tqdm, sugartensor
  Running setup.py install for sugartensor ... done
Successfully installed sugartensor-1.0.0.2 tqdm-4.11.2`

**# however**
when I run `python train.py`, it still error
`Traceback (most recent call last):
  File "train.py", line 1, in <module>
    import sugartensor as tf
ImportError: No module named sugartensor`

Could anyone help me ?

**Comment by guillaumekln** [comment]
Hi, I think you open this issue in the wrong repository.
