### ISSUE TITLE
translation_server.lua:{"error":"JoinTable.lua:38: inconsistent tensor size at THTensorCopy.c:17"}

### ISSUE THREAD

**Issue by netxiao** [OpenNMT/OpenNMT#284]
my script: 
`th tools/translation_server.lua -host 0.0.0.0  -port 9999  -n_best 5  -length_norm 0 -coverage_norm 1 -eos_norm 0 -model model_it.t7  -replace_unk -phrase_table pb.txt -log_level INFO`

send string to server:
`[{"src": "test it"}]`
recived msg:
`{"error":"JoinTable.lua:38: inconsistent tensor size at THTensorCopy.c:17"}`

**Comment by guillaumekln** [comment]
Could you give the full list of options used to train `model_it.t7`?

**Comment by netxiao** [comment]
my training config.ini file:
```
#src_vocab_size = 119970
#tgt_vocab_size =  90492
src_vocab = ./data/dict_src
tgt_vocab = ./data/dict_tgt


train_src = ./data/train_pcode/3.src
train_tgt = ./data/train_pcode/3.tgt

valid_src = ./data/valid/it_valid_20k.src
valid_tgt = ./data/valid/it_valid_20k.tgt

src_seq_length = 35
tgt_seq_length = 35


save_data = ./model/pcode
report_every = 5000

```

**Comment by guillaumekln** [comment]
This is a regression in torch/nn. I submitted a PR: https://github.com/torch/nn/pull/1220

**Comment by guillaumekln** [comment]
This has been merged. You should update `nn`:

```
luarocks install nn
```

**Comment by pdakwale** [comment]
I pulled a newer version of Open-NMT on January 5th and trained multiple models. While testing with any of the models gives similar error

/onmt/translate/BeamSearcher.lua:200: inconsistent tensor sizes at /tmp/luarocks_cutorch-scm-1-9140/cutorch/lib/THC/generic/THCTensorMath.cu:115

My training script:
th train.lua -data data/afp-bpe-data-train.t7 -save_model model/ldc-afp-model -src_word_vec_size 1000 -tgt_word_vec_size 1000 -rnn_size 1000 -gpuid 1

Test script : 

th translate.lua -model model/ldc-afp-model_epoch13_9.50.t7 -src test/mt09.arabic-english.src.tok_atb_mt.20kbpe.txt -output trans.ar-de.afp.mt09.epoch13.bpe.en -gpuid 1

Also updated torch and nn as suggested above. Still gives error
