### ISSUE TITLE
Control over features in input layer

### ISSUE THREAD

**Issue by raju249** [OpenNMT/OpenNMT#285]
Do I have a control over the number of features used by openNMT in RNN.
I checked the documentation but it's no where found. May be I am missing something.

I saw I can control the number of hidden layers, number of recurrent units in the RNN.
Can anyone help me with this ?

**Comment by guillaumekln** [comment]
What do you mean by "features" here?

**Comment by raju249** [comment]
I mean the parameters with which the networks is initialized 😅 .

**Comment by guillaumekln** [comment]
All options are listed here: http://opennmt.net/OpenNMT/options/train/

**Comment by raju249** [comment]
Ok,
Thanks 🙂
