### ISSUE TITLE
Potential issues in memory optimization

### ISSUE THREAD

**Issue by quanpn90** [OpenNMT/OpenNMT#299]
Hi,

Thanks for the great framework. 

I have looked at the memory optimization module and wonder if we need to unshare more modules. Some of them don't touch the input or output values during backward, but actually need to refer to their sizes. Take nn.Sum() for an example: it works fine currently since we can ensure that the input at every time step has the same dimension. However, it doesn't work if we have different input sizes, for example different attentional context sizes in local/hard attention. 

Not really a bug, but rather a warning. One possible remedy is to override necessary modules and store the sizes during forward passes to avoid that. 

Thanks,
Quan

**Comment by guillaumekln** [comment]
Hi,

Thanks for looking deep in the code!

You are correct, we only prevent the sharing of Tensors when their content is accessed and not their size. In the current implementation, the size constant during the forward and backward passes.

We should at least make the comments more explicit about this.

Thanks.

**Comment by pnquan90** [comment]
Hi, thanks for the response.

I have seen you updating the memory optimization script, that should be clear for anyone getting bugs when trying new methods. 

Best,
