### ISSUE TITLE
Potential bug in Encoder backward for uneven batches: 

### ISSUE THREAD

**Issue by quanpn90** [OpenNMT/OpenNMT#306]
Hi,

I tried to train several models with uneven batches, and noticed something for Encoder going backward:

- During forward, the finalStates are normally not the last states in the sequence (which is padded to the right). 
- During backward, looks like when we initialize the gradients for the finalStates, we also need to put the gradients into the position where we extracted the finalStates (currently it is default at the last position). Is it correct ? 

Best,
Quan

**Comment by guillaumekln** [comment]
Hi,

Thanks for reporting, this is indeed an issue.

However, sequences are padded on the left by default. So the problem only occurs when using `-brnn` where the input sequences are reversed.

I'm currently refactoring the padding management. I should take the opportunity to fix this inconsistency as well.
