### ISSUE TITLE
re-training break:__global__ function call is not configured

### ISSUE THREAD

**Issue by netxiao** [OpenNMT/OpenNMT#309]
Only appeared once.

training.ini:
```
sample = 900000
sample_type =  uniform
pre_word_vecs_enc =  data_it/train/it_src-embeddings-512.t7
pre_word_vecs_dec =  data_it/train/it_tgt-embeddings-512.t7
layers = 2
rnn_size = 512
max_batch_size = 128
optim = sgd
learning_rate = 0.2401
```
I have got errors:

> [06/04/17 00:22:36 INFO] Saving checkpoint to /tdisk/model/it2layer_checkpoint.t7'...	
> [06/04/17 00:23:38 INFO] Epoch 19 ; Iteration 3050/7055 ; Optim SGD LR 0.1681 ; Source tokens/s 1590 ; Perplexity 13.76	
> [06/04/17 00:24:21 INFO] Epoch 19 ; Iteration 3100/7055 ; Optim SGD LR 0.1681 ; Source tokens/s 2628 ; Perplexity 14.44	
> [06/04/17 00:24:56 INFO] Epoch 19 ; Iteration 3150/7055 ; Optim SGD LR 0.1681 ; Source tokens/s 2592 ; Perplexity 13.36	
> [06/04/17 00:25:36 INFO] Epoch 19 ; Iteration 3200/7055 ; Optim SGD LR 0.1681 ; Source tokens/s 2674 ; Perplexity 14.12	
> [06/04/17 00:26:13 INFO] Epoch 19 ; Iteration 3250/7055 ; Optim SGD LR 0.1681 ; Source tokens/s 2557 ; Perplexity 13.41	
> [06/04/17 00:26:48 INFO] Epoch 19 ; Iteration 3300/7055 ; Optim SGD LR 0.1681 ; Source tokens/s 2500 ; Perplexity 12.96	
> [06/04/17 00:27:24 INFO] Epoch 19 ; Iteration 3350/7055 ; Optim SGD LR 0.1681 ; Source tokens/s 2628 ; Perplexity 12.89	
> [06/04/17 00:28:01 INFO] Epoch 19 ; Iteration 3400/7055 ; Optim SGD LR 0.1681 ; Source tokens/s 2610 ; Perplexity 13.84	
> [06/04/17 00:28:35 INFO] Epoch 19 ; Iteration 3450/7055 ; Optim SGD LR 0.1681 ; Source tokens/s 2522 ; Perplexity 14.42	
> [06/04/17 00:29:16 INFO] Epoch 19 ; Iteration 3500/7055 ; Optim SGD LR 0.1681 ; Source tokens/s 2600 ; Perplexity 14.03	
> 
> THCudaCheck FAIL file=/torch/extra/cutorch/lib/THC/generic/THCStorage.c line=182 error=1 : __global__ function call is not configured
> /yfsys/work/torch/install/bin/lua: error in __gc metamethod (cuda runtime error (1) : __global__ function call is not configured at /torch/extra/cutorch/lib/THC/generic/THCStorage.c:182)
> 
>

**Comment by guillaumekln** [comment]
If you are not able to consistently reproduce it, consider closing this issue.
