### ISSUE TITLE
Attention Visualization

### ISSUE THREAD

**Issue by renzhe0009** [OpenNMT/OpenNMT#315]
Could anyone tell me how to get the attention matrix in the evaluate(decode) process?
Is the results[b].preds[n].attention = attn[b][n]  [code line](https://github.com/OpenNMT/OpenNMT/blob/master/onmt/translate/Translator.lua#L416)
I want to make Attention Visualization like http://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html#visualizing-attention
but pytorch-openNMT didn't implement additional word features yet.

Thank you in advance.

**Comment by guillaumekln** [comment]
> Is the results[b].preds[n].attention = attn[b][n] code line

Yes.

`attn[b][n]` corresponds to the attention of the `b`-th sentence in the batch and the `n`-th hypothesis. It is a table of `M` tensors of size `N`, where `N` is the source length and `M` the target length.

**Comment by renzhe0009** [comment]
Thanks! 
Then I think I can solve this.
