### ISSUE TITLE
tokenize.lua  removes sentences containing special characters

### ISSUE THREAD

**Issue by netxiao** [OpenNMT/OpenNMT#316]
when I use tokenize.lua to process corpus, I have got this result:

> Tokenization completed in 2437.165 seconds - 9650000 sentences
> Tokenization completed in 1762.637 seconds - 9649999 sentences

after I checked, I found that was a special character (\&#0;)  caused the problem.

please see attchment file [s1.txt](https://github.com/OpenNMT/OpenNMT/files/1065862/s1.txt)
line 61:
`the 9th international conference on low level measurements of actinides and long - lived radio �nuclides in biological and environ mental samples.`

**Comment by guillaumekln** [comment]
Thanks for reporting and providing the data. I reproduced the issue.

**Comment by guillaumekln** [comment]
Actually it is more than a special character, it is a null character (byte 0). So I'm more inclined to classify this input as invalid because even the Lua `read` primitive fails to completely read the line.

**Comment by netxiao** [comment]
thanks!  It is best to add the wrong line number on corpus, because it is very difficult to locate.
