### ISSUE TITLE
GPU memory continues to increase when training

### ISSUE THREAD

**Issue by netxiao** [OpenNMT/OpenNMT#317]
when I start to training, the GPU memory requirement is 4835MiB, after trained 2100 Iteration, the memory has grown to 5769MiB, and then I have got out of memory error.

> Iteration 200/8807
> |    0     26809    C   /yfsys/work/torch/install/bin/lua             4835MiB |
> 
>  Iteration 2100/8807
> |    0     26809    C   /yfsys/work/torch/install/bin/lua             5769MiB |

my GPU total memory is: 6000Mb.

I have tried `export THC_CACHING_ALLOCATOR=0`, but not much improvement.
my training config.ini:
```
max_batch_size = 128
optim = sgd
learning_rate = 1
decay =  default
sample = 3500000
sample_type =  uniform
layers = 4
encoder_type = gnmt
rnn_size = 1024
gpuid = 1
```
detail log informations:

> THCudaCheck FAIL file=/torch/extra/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
> /torch/install/bin/lua: /torch/install/share/lua/5.2/nngraph/nesting.lua:34: cuda runtime error (2) : out of m
> emory at /torch/extra/cutorch/lib/THC/generic/THCStorage.cu:66
> stack traceback:
>         [C]: in function 'resizeAs'
>         /torch/install/share/lua/5.2/nngraph/nesting.lua:34: in function 'resizeNestedAs'
>         /torch/install/share/lua/5.2/nngraph/gmodule.lua:37: in function 'getTotalGradOutput'
>         /torch/install/share/lua/5.2/nngraph/gmodule.lua:404: in function 'neteval'
>         /torch/install/share/lua/5.2/nngraph/gmodule.lua:454: in function 'updateGradInput'
>   ½     ...ork/torch/install/share/lua/5.2/onmt/modules/Network.lua:21: in function 'updateGradInput'
>         /torch/install/share/lua/5.2/nngraph/gmodule.lua:420: in function 'neteval'
>         /torch/install/share/lua/5.2/nngraph/gmodule.lua:454: in function 'updateGradInput'
>         /torch/install/share/lua/5.2/nn/Module.lua:31: in function 'backward'
>         ...ork/torch/install/share/lua/5.2/onmt/modules/Decoder.lua:440: in function 'backward'
>         /torch/install/share/lua/5.2/onmt/Seq2Seq.lua:232: in function 'trainNetwork'
>         .../work/torch/install/share/lua/5.2/onmt/train/Trainer.lua:202: in function 'closure'
>         ...work/torch/install/share/lua/5.2/onmt/utils/Parallel.lua:79: in function 'launch'
>         .../work/torch/install/share/lua/5.2/onmt/train/Trainer.lua:189: in function 'trainEpoch'
>         .../work/torch/install/share/lua/5.2/onmt/train/Trainer.lua:382: in function 'train'
>         train.lua:173: in function 'main'
>         train.lua:178: in main chunk
>         [C]: in function 'dofile'
>         ...work/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
>         [C]: in ?

**Comment by guillaumekln** [comment]
The memory usage grows during the first epoch to fit unseen sequence lengths. In any case, 6GB is not enough for the training parameters you set. You can start by reducing the batch size to a smaller value, like 32.

**Comment by netxiao** [comment]
thanks!
