### ISSUE TITLE
error constructing batches using pdbrnn_reduction > 1

### ISSUE THREAD

**Issue by esalesky** [OpenNMT/OpenNMT#321]
I'm trying to train a model with feattext input and character output using pdbrnn, but getting an error when training batches are constructed. It looks like the issue is resizing the source to make sure it's divisible by the reduction. I tried with pdbrnn_reduction = 2 and got the error below. When I set pdbrnn_reduction = 1 it will train. I get the same error with batch_size = 1 as batch_size = 24. 

I'm running from a recent pull (https://github.com/OpenNMT/OpenNMT/commit/7540f810da54e671c4fc547f776467ed04245dce) so this is after the recent pdbrnn / padding changes, and is a different error than #224 

$ CUDA_VISIBLE_DEVICES=0 THC_CACHING_ALLOCATOR=0 th train.lua -data init40.1-train.t7 -save_model init40.1 -config init40.config -gpuid 1
> ./onmt/data/Batch.lua:283: bad argument #1 to 'copy' (sizes do not match at /home/esalesky/torch/extra/cutorch/lib/THC/THCTensorCopy.cu:31)
stack traceback:
        [C]: in function 'copy'
        ./onmt/data/Batch.lua:283: in function 'resizeSource'
        ./onmt/modules/PDBiEncoder.lua:119: in function 'forward'
        ./onmt/Seq2Seq.lua:205: in function 'trainNetwork'
        ./onmt/utils/Memory.lua:40: in function 'optimize'
        ./onmt/train/Trainer.lua:102: in function '__init'
        .../torch/install/share/lua/5.2/torch/init.lua:91: in function 'new'
        train.lua:172: in function 'main'
        train.lua:178: in main chunk
        [C]: in function 'dofile'
        ...orch.fresh/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: in ?

**Comment by guillaumekln** [comment]
Thanks for reporting this, it should be fixed on master.

**Comment by esalesky** [comment]
Great, thank you.
