### ISSUE TITLE
score.lua crashed when line count hyp/ref does not match

### ISSUE THREAD

**Issue by jinsystran** [OpenNMT/OpenNMT#324]
score.lua crashed when line count hyp/ref does not match

/usr/local/torch/install/bin/luajit: tools/score.lua:96: ERROR: line count hyp/ref does not match
stack traceback:
        [C]: in function 'assert'
        tools/score.lua:96: in function 'main'
        tools/score.lua:105: in main chunk
        [C]: in function 'dofile'
        ...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x004064f0

how to reproduce:  make the hyp/ref has different line count

**Comment by jsenellart** [comment]
this was fixed with #335
