### ISSUE TITLE
learn_bpe error

### ISSUE THREAD

**Issue by nnjesse** [OpenNMT/OpenNMT#339]
[07/10/17 15:30:43 INFO] ... 6400000 sentences processed	
[07/10/17 15:30:49 INFO] ... 6500000 sentences processed	
lua: unable to convert argument 2 from cdata<int (*)(struct tds_elem_*, struct tds_elem_*)> to cdata<int (*)(const struct tds_elem_*, const struct tds_elem_*)>

this error occurs after upgrading to a new version cd4b16c979aeeb01cc03339830c6451fa1a6c86a

**Comment by guillaumekln** [comment]
This seems to be an issue related to Lua 5.2. See: https://github.com/torch/tds/issues/25.

I suggest you to use LuaJIT in the meantime, @mousai worked to bypass the memory limit we encountered.
