### ISSUE TITLE
learn_bpe.lua crashes after processing

### ISSUE THREAD

**Issue by gugray** [OpenNMT/OpenNMT#351]
I am broadly following the "Training Romance Multi-Way model" tutorial. I issue the command below on the raw tokenized corpus:

`th tools/learn_bpe.lua -size 50000 -save_bpe 01-enhu/data/all.bpe50000 < 01-enhu/data/all.rawtok`

After much processing, the result is not saved; instead I get the error below:

```
/home/ug/torch/install/bin/lua: unable to convert argument 2 from cdata<int (*)(struct tds_elem_*, struct tds_elem_*)> to cdata<int (*)(const struct tds_elem_*, const struct tds_elem_*)>
stack traceback:
        [C]: in function 'tds_vec_sort'
        /home/ug/torch/install/share/lua/5.2/tds/vec.lua:98: in function 'sort'
        tools/learn_bpe.lua:258: in function 'main'
        tools/learn_bpe.lua:283: in main chunk
        [C]: in function 'dofile'
        ...e/ug/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: in ?
```

Error seems to be cause by the commit below. If I revert to the version before that commit, the script finishes without the error.

Changed various tables to tds.Vec or tds.Hash to avoid issues with LuaJIT's 2GB heap limit
ccd7e03395c3e07cfc785f8434a916bc98a366a2

**Comment by guillaumekln** [comment]
Related to https://github.com/OpenNMT/OpenNMT/issues/339. The error is raised when using Lua 5.2.

@mousai Maybe we should take care of this. Either with a workaround or a proper fix in `tds`.

**Comment by guillaumekln** [comment]
To update on this issue, I submitted a fix to torch/tds a few weeks ago but the repo does not seem to be maintained actively.

You can still checkout the PR and install it manually if you need to stick with Lua 5.2 for some reasons:

https://github.com/torch/tds/pull/32

**Comment by guillaumekln** [comment]
This is finally fixed. Simply update `tds`:

```
luarocks install tds
```
