### ISSUE TITLE
Is there anyone who can tell me what's the strategy to replace unk in the translate.lua?

### ISSUE THREAD

**Issue by gladuo** [OpenNMT/OpenNMT#354]
[Here](https://github.com/OpenNMT/OpenNMT/blob/master/onmt/translate/Translator.lua#L246-L250) I found this piece of code is used to replace unk, but I am not sure how does it work ? What's the meaning of _ and maxIndex in 246L and how can we find the "source" in a seq2seq code.

**Comment by guillaumekln** [comment]
I think the documentation is helpful for that: http://opennmt.net/OpenNMT/translation/unknowns/

> What's the meaning of _ and maxIndex in 246L

This is just syntax (`_` is used to ignore a returned value). Also see the documentation of [`torch.max`](https://github.com/torch/torch7/blob/master/doc/maths.md#torchmaxresval-resind-x-dim).
