### ISSUE TITLE
GPU identifier validation mistakenly rejects valid configuration

### ISSUE THREAD

**Issue by cshapeshifter** [OpenNMT/OpenNMT#357]
[Here](https://github.com/OpenNMT/OpenNMT/blob/master/onmt/utils/Cuda.lua#L49), Cuda.lua does the following check:

```
for i = 1, #Cuda.gpuIds do
  assert(Cuda.gpuIds[i] <= cutorch.getDeviceCount(),
  'GPU ' .. Cuda.gpuIds[i] .. ' is requested but only '
  .. cutorch.getDeviceCount() .. ' GPUs are available')
```
But this doesn't actually make sense. Consider the following scenario:

- There's a server with 8x Teslka K80 cards with a total of 16 GPU cores. It runs SLURM for job scheduling.
- Some other person is using 6 GPU cores, e.g. GPUs 0, 1, 2, 8, 9, 10.
- I want to use the remaining 10 GPUs (3, 4, 5, 6, 7, 11, 12, 13, 14, 15, which is what ```echo "$CUDA_VISIBLE_DEVICES"``` returns)
- ```cutorch.getDeviceCount()``` returns 10 (16-6) because that's what I configure in SLURM.
- But the GPUs I need to use include those with IDs higher than 10 so the assertion above fails on ```11 <= 10```

There would be enough GPU cores but the highest value in  Cuda.gpuIds would be 16, even though only 10 GPUs are available. The assertion fails and I can't proceed.

I tried just removing that check, but then it fails with:

```
[08/11/17 18:47:05 INFO] Using GPU(s): 3, 4, 5, 6, 7, 11, 12, 13, 14, 15
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-1130/cutorch/init.c line=734 error=10 : invalid device o
rdinal
/net/nfs4/nfs.hydra/home/user/torch/install/bin/lua: ...e/user/torch/install/share/lua/5.2/threads/thr
eads.lua:183: [thread 7 callback] ./onmt/utils/Cuda.lua:69: ./onmt/utils/Cuda.lua:57: cuda runtime error (
10) : invalid device ordinal at /tmp/luarocks_cutorch-scm-1-1130/cutorch/init.c:734
stack traceback:
        [C]: in function 'error'
        ./onmt/utils/Cuda.lua:69: in function 'init'
        ./onmt/utils/Parallel.lua:52: in function <./onmt/utils/Parallel.lua:49>
        (...tail calls...)
        [C]: in function 'xpcall'
        ...e/user/torch/install/share/lua/5.2/threads/threads.lua:234: in function 'callback'
        ...ome/user/torch/install/share/lua/5.2/threads/queue.lua:65: in function <...ome/user/torch/i
nstall/share/lua/5.2/threads/queue.lua:41>
        [C]: in function 'pcall'
        ...ome/user/torch/install/share/lua/5.2/threads/queue.lua:40: in function 'dojob'
        [string "  local Queue = require 'threads.queue'..."]:13: in main chunk
stack traceback:
        [C]: in function 'error'
        ...e/user/torch/install/share/lua/5.2/threads/threads.lua:183: in function 'dojob'
        ...e/user/torch/install/share/lua/5.2/threads/threads.lua:264: in function 'synchronize'
        ...e/user/torch/install/share/lua/5.2/threads/threads.lua:142: in function 'specific'
        ...e/user/torch/install/share/lua/5.2/threads/threads.lua:125: in function <...e/user/torch/in
stall/share/lua/5.2/threads/threads.lua:36>
        (...tail calls...)
        ./onmt/utils/Parallel.lua:41: in function 'init'
        train.lua:141: in function 'main'
        train.lua:178: in main chunk
        [C]: in function 'dofile'
        ...lexa/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: in ?
srun: error: vesta2: task 0: Exited with exit code 1
```

So I guess the problem goes deeper than that, but at least that assertion doesn't make sense. Comparing ```cutorch.getDeviceCount()``` to the selected GPU cores doesn't work in a shared environment. If anything, the selected GPUs should probably be compared to the available GPUs contained in ```$CUDA_VISIBLE_DEVICES```.

**Comment by guillaumekln** [comment]
Hi,

`-gpuid` accepts the GPU identifiers as **visible by your process**. So for example:

```
CUDA_VISIBLE_DEVICES=3,5,7 th train.lua [...] -gpuid 1 3
```

will use the first and third GPU, namely GPUs 3 and 7. This is briefly covered in the documentation:

http://opennmt.net/OpenNMT/training/multi_gpu/

> `th train.lua -data data/demo-train.t7 -save_model demo -gpuid 1 2 4`
>
> will use the first, the second and the fourth GPU of the machine as returned by the CUDA API.

I guess we could read the environment variable but here you can keep the same command line (e.g. `-gpuid 1 2 3`) and set `CUDA_VISIBLE_DEVICES` to configure which are the 3 GPUs to use.

**Comment by cshapeshifter** [comment]
Oh I see. Sorry about that. Imo the wording isn't clear though. The example you made makes it clear. So no matter which GPUs (in terms of IDs) are available, one essentially needs to pass 1 2 3 4 5 ... up to the number of GPUs desired and available.
