### ISSUE TITLE
Tokenization

### ISSUE THREAD

**Issue by lpzreq** [OpenNMT/OpenNMT#361]
I train model with case_feature. And try send data to rest server:  [{"src": "привет"}]
And get response from server:
  "tgt": "Hi .", "src": "привет￨C"

Why detokinization put space beetwen word and dot?

**Comment by guillaumekln** [comment]
I think you want to train a model on data tokenized with the `-joiner_annotate` flag. Otherwise the detokenizer has no information on how to merge tokens.

**Comment by lpzreq** [comment]
I train model with only case_feature. 
I should retrain with -joiner_annotate flag? But if i set to true -joiner_annotate flag, i must set -joiner  to something?

**Comment by guillaumekln** [comment]
> I should retrain with -joiner_annotate flag?

If you want to handle this detokenization behavior, yes.

> But if i set to true -joiner_annotate flag, i must set -joiner to something?

You can just rely on the default value.

**Comment by lpzreq** [comment]
Thanks, i try this.

**Comment by lpzreq** [comment]
For OpenNMT no problem now. Thanks. Problem closed.
