### ISSUE TITLE
Installation problem?

### ISSUE THREAD

**Issue by Gldkslfmsd** [OpenNMT/OpenNMT#378]
Current master branch quickstart:

```
obo-machacek@large09:~/OpenNMT$ th preprocess.lua -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo
/home/obo-machacek/torch/install/bin/luajit: .../obo-machacek/torch/install/share/lua/5.1/trepl/init.lua:389: .../obo-machacek/torch/install/share/lua/5.1/trepl/init.lua:389: .../obo-machacek/torch/install/share/lua/5.1/trepl/init.lua:389: .../obo-machacek/torch/install/share/lua/5.1/trepl/init.lua:389: .../obo-machacek/torch/install/share/lua/5.1/trepl/init.lua:389: .../obo-machacek/torch/install/share/lua/5.1/trepl/init.lua:389: module 'bit32' not found:No LuaRocks module found for bit32
	no field package.preload['bit32']
	no file '/home/obo-machacek/.luarocks/share/lua/5.1/bit32.lua'
	no file '/home/obo-machacek/.luarocks/share/lua/5.1/bit32/init.lua'
	no file '/home/obo-machacek/torch/install/share/lua/5.1/bit32.lua'
	no file '/home/obo-machacek/torch/install/share/lua/5.1/bit32/init.lua'
	no file './bit32.lua'
	no file '/home/obo-machacek/torch/install/share/luajit-2.1.0-beta1/bit32.lua'
	no file '/usr/local/share/lua/5.1/bit32.lua'
	no file '/usr/local/share/lua/5.1/bit32/init.lua'
	no file '/home/obo-machacek/.luarocks/lib/lua/5.1/bit32.so'
	no file '/home/obo-machacek/torch/install/lib/lua/5.1/bit32.so'
	no file '/home/obo-machacek/torch/install/lib/bit32.so'
	no file './bit32.so'
	no file '/usr/local/lib/lua/5.1/bit32.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	.../obo-machacek/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	preprocess.lua:1: in main chunk
	[C]: in function 'dofile'
	...acek/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
```

But it works with latest release. ;)

**Comment by jsenellart** [comment]
Hi @Gldkslfmsd - you just need to install `bit32` module:

```
luarocks install bit32
```

are you sure it works with the same torch installation with a previous release?

**Comment by Gldkslfmsd** [comment]
Hi!
I tried `luarocks install bit32` and it didn't work, there was another problem. And if this is necessary then insert it to installation manual.
Few days ago I made an installation script to install torch and OpenNMT from GitHub master to a brand new machine. It worked few days ago but yesterday it failed. I solved it by using latest release instead of master. But maybe the bug is on my side, now I know there were some issues with permissions on my machines :(
Anyway, I'm sorry I can't invest my time to this issue unless I get another machine or it fails again.

**Comment by jsenellart** [comment]
@guillaumekln - can you double check that I did not introduce anything problematic around bit32? I don't see anything from my end - the only new thing is that Preprocess is now systematically going through threads. thanks

**Comment by guillaumekln** [comment]
@Gldkslfmsd 

> I tried `luarocks install bit32` and it didn't work, there was another problem.

Was the `bit32` installation that did not work or the preprocessing that still did not work after installing `bit32`? If the latter, what was the new error?

@jsenellart I will update the documentation to reflect this new dependency.

**Comment by Gldkslfmsd** [comment]
@guillaumekln 
I've just replicated the issue. It works after installing bit32.
