### ISSUE TITLE
Quickstart error, both on Ubuntu and Macos

### ISSUE THREAD

**Issue by urialon** [OpenNMT/OpenNMT#379]
Hi,
The following error occurs both on MacOS with torch that I installed myself, and both on EC2 (p2 vm) with Deep Learning AMI (Ubuntu):

I am following the [Quickstart](http://opennmt.net/OpenNMT/quickstart/) , and getting the following error right after running the preprocessing command for the demo quickstart:
`th preprocess.lua -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo`

> ubuntu@ip-172-31-43-121:~/OpenNMT$ th preprocess.lua -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo
[09/17/17 08:17:08 INFO] Using on-the-fly 'space' tokenization for input 1	
[09/17/17 08:17:08 INFO] Using on-the-fly 'space' tokenization for input 2	
[09/17/17 08:17:08 INFO] Preparing vocabulary...	
[09/17/17 08:17:08 INFO]  * Building source vocabularies...	
[09/17/17 08:17:08 INFO]  * Created word dictionary of size 24999 (pruned from 24999)	
[09/17/17 08:17:08 INFO] 	
[09/17/17 08:17:08 INFO]  * Building target vocabularies...	
[09/17/17 08:17:08 INFO]  * Created word dictionary of size 35820 (pruned from 35820)	
[09/17/17 08:17:08 INFO] 	
[09/17/17 08:17:08 INFO] Preparing training data...	
[09/17/17 08:17:08 INFO] --- Preparing train sample	
/home/ubuntu/src/torch/install/bin/luajit: ./onmt/utils/Features.lua:14: attempt to index local 'word' (a nil value)
stack traceback:
	./onmt/utils/Features.lua:14: in function 'extract'
	./onmt/data/Preprocessor.lua:525: in function 'processSentence'
	./onmt/data/Preprocessor.lua:673: in function 'f'
	./onmt/data/Preprocessor.lua:356: in function 'poolAddJob'
	./onmt/data/Preprocessor.lua:583: in function 'makeGenericData'
	./onmt/data/Preprocessor.lua:820: in function 'makeBilingualData'
	./onmt/data/Preprocessor.lua:983: in function 'makeData'
	preprocess.lua:63: in function 'main'
	preprocess.lua:103: in main chunk
	[C]: in function 'dofile'
	.../src/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

is there something wrong with the tutorial? I don't think I missed anything. I did have to install "luarocks install bit32" although it wasn't on the instructions.

Thanks!

**Comment by vince62s** [comment]
can you try to check out on this hash instead https://github.com/OpenNMT/OpenNMT/commit/2f25996858826769dafd2b806dcd23cc138798c5

**Comment by urialon** [comment]
This commit works, thanks.

**Comment by vince62s** [comment]
@jsenellart your commit with dynamic dataset has a bug I think.

**Comment by jsenellart** [comment]
Thanks @urialon and @vince62s - it is fixed.
