### ISSUE TITLE
how to transfer the model that was trained by lua5.2 to lua5.1

### ISSUE THREAD

**Issue by beichao1314** [OpenNMT/OpenNMT#38]
the model was trained by lua5.2, how to reload by lua5.1? I tried it but get the error:
Warning: Failed to load function from bytecode: (binary): cannot load incompatible bytecode.

**Comment by guillaumekln** [comment]
Can you share the OpenNMT and Torch revisions you used in both cases? I can't reproduce the issue.

For reference, it can happen when the model has [serialized functions](https://github.com/torch/torch7/issues/641) which should not be the case with OpenNMT.

**Comment by guillaumekln** [comment]
I think I reproduced it. @beichao1314 Can you confirm you used the `-brnn` option?

It seems to happen when sharing parameters. Calling `share(...)` stores a function as a new field: https://github.com/torch/nn/blob/master/Module.lua#L98-L99

**Comment by beichao1314** [comment]
I'm sorry I'm late to reply.
Yes, I use the -brnn option.
Finally, I reload the model which was trained by lua5.2 by lua5.2, not lua5.1.

**Comment by guillaumekln** [comment]
Good. I submitted a [patch](https://github.com/torch/nn/pull/1092) to `torch/nn` to fix this issue.
