### ISSUE TITLE
ERROR: all data sources do not have the same number of sentences

### ISSUE THREAD

**Issue by urialon** [OpenNMT/OpenNMT#383]
Hi,
I'm running preprocessing on my own source and target data files. 
The vocabularies are built successfully, but after the beginning of "Preparing train sample" I am getting the following error:
**all data sources do not have the same number of sentences**

I don't exactly understand what it means, because I looked at the code and it seems that the check for same number of lines in the source and target files is done somewhere else.
I verified that:

1. Source and target files have exactly the same number of lines.
2. The data doesn't contain the special symbols (< s >, < unk >, < blank >, < /s >)
3. There are no empty lines in the source or target

Any idea what can it be? 
Or more generally - how is that possible that the src&tgt have the same number of lines but not the same number of sentences?

I'm running the preprocessing code with the following flags:
-train_src my_src.txt 
-train_tgt my_tgt.txt 
-valid_src my_valid_src.txt 
-valid_tgt my_valid_tgt.txt 
-save_data my_save 
-src_words_min_frequency 9 
-tgt_words_min_frequency 1 
-src_seq_length 400 
-tgt_seq_length 10

Thanks!

**Comment by guillaumekln** [comment]
Hello,

How did you check that source and target files have the number of lines?

**Comment by urialon** [comment]
Hi, with simple bash:

wc -l my_src.txt my_tgt.txt
(which showed the same number)

and verified that there are no empty lines using:
cat my_src.txt | awk '(NF == 0)' | wc -l
(which showed zero for both files)

Thanks

**Comment by guillaumekln** [comment]
Did you check the validation files as well?

**Comment by urialon** [comment]
Yes, also checked validation source and target, even though the error occurs while preprocessing the training data.

**Comment by jsenellart** [comment]
I reviewed the code around this, and do not see anything wrong, are you on the master? if yes can you check on the last release? is your corpus shareable? if no can you try to narrow down by splitting the corpus? Thanks

**Comment by urialon** [comment]
Hi,
Thanks to your advice I narrowed down the corpus and found one of the problems - the character '@'. When it appears in the training data it messes things up, even in a very small data (2-3 lines).

However, even after deleting this character from everywhere it appears, (using sed) I am still getting the same error. Any idea what other kinds of non-alphabetic characters might cause this problem in the file reader?

Thanks!

**Comment by guillaumekln** [comment]
I think it is related to #316.

Could you check that your files do not contain zero bytes (a.k.a the null character `\0`)?

**Comment by urialon** [comment]
Thanks a lot! that was it. 
For future reference - I removed the null character from my data using:
sed -i 's/\x0//g' myfile.txt

I recommend to add a note to the docs...

**Comment by ljy296566** [comment]
Thanks a lot! 
I have same problem with you, and I fix it with your command.
