### ISSUE TITLE
tok_(src|tgt)_case_feature + DynData training doesn't work with translation_server

### ISSUE THREAD

**Issue by EtienneAb3d** [OpenNMT/OpenNMT#384]
When a model is trained with a dynamic data set, and tok_src_case_feature / tok_tgt_case_feature options, if a tokenized sentence with case feature is sent to the translation_server, its ouput provides with the right translation, but that neither contains the case features, nor the right case where needed.

**Comment by jsenellart** [comment]
bad news is that training was ignoring the case feature - even if `-tok_src_case_feature` and `-tok_tgt_case_feature` were set if no feature vocabulary were provided. case feature dictionary is now systematically built.
Note that you need to have your vocabulary built with corpus tokenized with `-case_feature`: we will drop that soon by introducing tokenization options in `build_vocab.lua`

**Comment by EtienneAb3d** [comment]
Test running...

**Comment by EtienneAb3d** [comment]
Having done a proper clone of the current master branch, I still get this error.
:-/

**Comment by jsenellart** [comment]
ok I reproduce sorry - will get that fixed tonight (Xi'an time).

**Comment by jsenellart** [comment]
second version (not merged) - can you double check Etienne?

**Comment by EtienneAb3d** [comment]
Epoch is now properly starting. 
Waiting for a model to test the whole behaviour related to this issue...
;-)

**Comment by EtienneAb3d** [comment]
First differences:
- features are now produced in the validation translation file, at the end of each epoch (this wasn't the case before)
- GPU RAM used is higher (I got nearly 1M left before, only few K now... certainly I will be obliged to reduce the batch size)

**Comment by EtienneAb3d** [comment]
(forget the last post, deleted.. I had a previous model that was still running for translation)
Features are now produced in the validation translation file, at the end of each epoch (this wasn't the case before), and also in the translation server.
Issue solved !
THANKS !
:)
