### ISSUE TITLE
What is "cleaned" newstest2014?

### ISSUE THREAD

**Issue by dennybritz** [OpenNMT/OpenNMT#39]
Hi,

On the models page you evaluate on `newstest2014 (cleaned)`. What exactly does "cleaned" mean here?

**Comment by jsenellart-systran** [comment]
it is the test set referenced here http://www.statmt.org/wmt14/translation-task.html as "Cleaned Test Sets".

**Comment by dennybritz** [comment]
I see, so this is the regular `newstest2014` for WMT15/16. What confused me is this [tgt-test.txt](https://github.com/OpenNMT/OpenNMT/blob/master/data/tgt-test.txt) file in the repo. It seems to have fewer examples than the official `newstest2014`?
