### ISSUE TITLE
Issue running preprocess.lua

### ISSUE THREAD

**Issue by raymondhs** [OpenNMT/OpenNMT#394]
Hi, I got the following error when executing preprocess.lua. I already included `-save_data <prefix>` in my command.

```
preprocess.lua: invalid dependency for option -save_data: option `-save_data` is required
Try 'preprocess.lua -h' for more information, or visit the online documentation at http://opennmt.net/OpenNMT/.
```

I'm guessing is it related to the recently added `-dry_run` feature?

**Comment by guillaumekln** [comment]
Thanks for reporting. It is fixed.
