### ISSUE TITLE
Ensemble decoding

### ISSUE THREAD

**Issue by raymondhs** [OpenNMT/OpenNMT#400]
I'm interested in ensembling a few models trained using OpenNMT. Is there some ways to do this at the moment? I noticed there was some work, but not sure why it is not merged yet: http://forum.opennmt.net/t/ensemble-decoding/115/11.

Thanks!

**Comment by guillaumekln** [comment]
There is a branch based on an older version if you are interested: https://github.com/OpenNMT/OpenNMT/pull/300

However, it is not efficient and usually does not improve the results notably. It seems to indicate that OpenNMT final models are already good enough.

You might also want to checkout model averaging with `tools/average_models.lua`. It is an alternative and simpler way to simulate model ensembling.
