### ISSUE TITLE
train process so slow Iam using cpu "core i7" on ubuntu

### ISSUE THREAD

**Issue by sondos90** [OpenNMT/OpenNMT#409]
is it normal that the train process takes so much time ?
like from epoch 1 50/184 to epoch 2 50/184 took 1 day and half hour
I am using OpenNMT-r0.6 with its data

**Comment by guillaumekln** [comment]
Sorry, you should get a GPU to train a system in a reasonable amount of time.

**Comment by sondos90** [comment]
could you please advise me about the GPU  requirements  that i should have to be enough within budgets around 700$
