### ISSUE TITLE
Error in training

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/OpenNMT#415]
Here is my scenario:
I trained a BPE model, then ran a regular training on corpus A.
I then want to pursue training on corpus B, following the command:
       th train.lua -train_from mymodel.t7 \
        -train_src B.$sl -train_tgt B.$tl \
        -src_vocab data/dict.$sl.dict -tgt_vocab data/dict.$tl.dict \
        -valid_src data/valid.$sl.tok -valid_tgt data/valid.$tl.tok \
        -tok_src_bpe_model data/train-$sl$tl.bpe32000 \
        -tok_tgt_bpe_model data/train-$sl$tl.bpe32000 \
        -sample $sample -sample_type partition \
        -save_model exp/model-special-$sl$tl \
        -start_epoch $epoch -end_epoch $final_epoch -max_batch_size $batch3 \
        -optim $optim \
        -learning_rate $final_lr -start_decay_at $start_decay_at -decay epoch_only \
        -learning_rate_decay 1 -save_every_epochs 10 -gpuid $gpuid  

It throws the following error:

[10/30/17 14:12:15 INFO] Loading checkpoint 'mymodel.t7'...
[10/30/17 14:12:20 INFO] Preparing memory optimization...	
/home/moses/torch/install/bin/luajit: /home/moses/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 1 module of nn.Sequential:
In 1 module of nn.ParallelTable:
/home/moses/torch/install/share/lua/5.1/nn/LookupTable.lua:59: attempt to index local 'input' (a number value)
stack traceback:
	/home/moses/torch/install/share/lua/5.1/nn/LookupTable.lua:59: in function 'makeInputContiguous'
	/home/moses/torch/install/share/lua/5.1/nn/LookupTable.lua:71: in function 'updateOutput'
	./onmt/modules/Network.lua:16: in function <./onmt/modules/Network.lua:15>
	[C]: in function 'xpcall'
	/home/moses/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	...e/moses/torch/install/share/lua/5.1/nn/ParallelTable.lua:12: in function <...e/moses/torch/install/share/lua/5.1/nn/ParallelTable.lua:10>
	[C]: in function 'xpcall'
	/home/moses/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/moses/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'func'
	/home/moses/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	...
	./onmt/modules/BiEncoder.lua:153: in function 'forward'
	./onmt/Seq2Seq.lua:209: in function 'trainNetwork'
	./onmt/utils/Memory.lua:39: in function 'optimize'
	./onmt/train/Trainer.lua:133: in function '__init'
	/home/moses/torch/install/share/lua/5.1/torch/init.lua:91: in function 'new'
	train.lua:193: in function 'main'
	train.lua:199: in main chunk
	[C]: in function 'dofile'
	...oses/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/home/moses/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/home/moses/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'func'
	/home/moses/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	/home/moses/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
	./onmt/modules/Encoder.lua:240: in function 'forward'
	./onmt/modules/BiEncoder.lua:153: in function 'forward'
	./onmt/Seq2Seq.lua:209: in function 'trainNetwork'
	./onmt/utils/Memory.lua:39: in function 'optimize'
	./onmt/train/Trainer.lua:133: in function '__init'
	/home/moses/torch/install/share/lua/5.1/torch/init.lua:91: in function 'new'
	train.lua:193: in function 'main'
	train.lua:199: in main chunk
	[C]: in function 'dofile'
	...oses/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670

**Comment by guillaumekln** [comment]
Did the first training on corpus A use case features?

**Comment by vince62s** [comment]
yes

**Comment by guillaumekln** [comment]
Then you should enable case features for this training as well using the appropriate tokenizer flags (`-tok_{src,tgt}_case_feature`) and the `-features_vocabs_prefix` option.

**Comment by vince62s** [comment]
okay, the -features_vocabs_prefix option expect a prefix but the file name used at preprocess time does not match the same pattern.
I had to rename the feature file but I think it should be fixed in a different way.
