### ISSUE TITLE
[proposal] Add HDF5 support

### ISSUE THREAD

**Issue by anoidgit** [OpenNMT/OpenNMT#418]
I have 20 million sentence pairs, loading these data will consume much time and a large proportion of memory. I hope that this library can add the support of HDF5 as an option, thereby lowering resource requirement.

**Comment by jsenellart** [comment]
hello - are you using the lua version or the pytorch one? for the lua version, look at dynamic dataset which workaround the problem by not loading all the dataset in memory: http://forum.opennmt.net/t/dynamic-dataset/746

**Comment by anoidgit** [comment]
Sorry for I forget about this issue after I try your helpful advice. @jsenellart
