### ISSUE TITLE
Services created using the screen command cannot request

### ISSUE THREAD

**Issue by sdlmw** [OpenNMT/OpenNMT#421]
hello everybody
    I have a problem.When i use the screen command  to create a backend terminal.I can't request this port on another machine.I'm sure this port is open.And the system and OPENNMT are normal.Could you please explain this to me, thank you very much.

**Comment by guillaumekln** [comment]
Hello,

I'm not sure what is the issue you are describing. Is it an OpenNMT issue?

If yes, please include the commands and options you used.
If not, you can still post on the forum, maybe some people are using the same tools as you.

**Comment by sdlmw** [comment]
hi， @guillaumekln 
this command: th tools/rest_translation_server.lua -joiner_annotate -port 4069 -model

**Comment by guillaumekln** [comment]
Try setting `-host 0.0.0.0` on your command line.

**Comment by sdlmw** [comment]
yeah, it is ok.  thanks @guillaumekln
