### ISSUE TITLE
OpenNMT not working on Python in Windows

### ISSUE THREAD

**Issue by LoekvanKooten** [OpenNMT/OpenNMT#432]
python -m bin.main train --model config/models/nmt_small.py --config config/opennmt-defaults.yml config/data/xxx.yml

...whereby xxx is the name of the yaml file in question...

...does start the training, but returns to the prompt a few seconds later. This while building the vocabulary does not cause any problems and works correctly. 

This is when sitecustomize.py is added to Python36/Lib stating:

import sys
import codecs
sys.stdout = codecs.getwriter(‘utf8’)(sys.stdout)
sys.stderr = codecs.getwriter(‘utf8’)(sys.stderr)

Without sitecustomize.py the training starts too, but then throws an error:

UnicodeDecodeError: ‘cp932’ codec can’t decode byte 0xef in position xxxx: illegal multibyte sequence

This time though, the actual model directory is created (it only contains a 2K file though).

With sitecustomize.py, this directory is not created.

**Comment by guillaumekln** [comment]
Closing this one as it refers to OpenNMT-tf, not OpenNMT.
