### ISSUE TITLE
Variable Length Encoder Support

### ISSUE THREAD

**Issue by anoidgit** [OpenNMT/OpenNMT#439]
Hi, I have just implemented another `SoftMax` module called `LenSoftMax` and its CUDA version. And there are the libraries:
https://github.com/anoidgit/lenn
https://github.com/anoidgit/culenn
It takes a Lua table as input, which looks like that:
 `{batchsize*maxseqlen(torch.(Cuda)Tensor), batchsize(torch.(Cuda)LongTensor)}`
The numbers in the second vector are the actual lengths of each sequence, softmax function are limited in that length, and 0 will be filled to the padding positions.
So, I think if we could do several changes to 'onmt.modules.GlobalAttention' and related files, Encoder would be allowed to take a batch of data of different sequence lengths as input.
But I am not sure whether these changes are valuable or not, extra dependencies will be added if we want to apply these changes. Actually, these modules are prepared for Attention-over-Attention module for reading comprehension, without these modules, it can not take batch data as input.

**Comment by guillaumekln** [comment]
Hi,

Thanks for sharing that. We actually implemented a [custom `nngraph` module](https://github.com/OpenNMT/OpenNMT/blob/master/onmt/modules/MaskedSoftmax.lua) that handles variable length inputs. At each iteration, we update the module to fit the current sequence length distribution and it makes sure that no weight is given to padding position.

**Comment by anoidgit** [comment]
That's good, if I have known that there is already a solution, I would not have to change the C/C++ code of `nn` and `cunn` anymore. @guillaumekln
