### ISSUE TITLE
docker image lack some module

### ISSUE THREAD

**Issue by wsnooker** [OpenNMT/OpenNMT#44]
hi, some errors occur when i using the pulled opennmt docker image. Since i am not used to lua, this error is hard for me to resolve. Can anybody give me a help... 

root@5b63449e0fe8:/home/ww110750/OpenNMT# th preprocess.lua -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/trepl/init.lua:389: /root/torch/install/share/lua/5.1/trepl/init.lua:389: /root/torch/install/share/lua/5.1/trepl/init.lua:389: /root/torch/install/share/lua/5.1/trepl/init.lua:389: module 'tds' not found:No LuaRocks module found for tds
        no field package.preload['tds']
        no file '/root/.luarocks/share/lua/5.1/tds.lua'
        no file '/root/.luarocks/share/lua/5.1/tds/init.lua'
        no file '/root/torch/install/share/lua/5.1/tds.lua'
        no file '/root/torch/install/share/lua/5.1/tds/init.lua'
        no file './tds.lua'
        no file '/root/torch/install/share/luajit-2.1.0-beta1/tds.lua'
        no file '/usr/local/share/lua/5.1/tds.lua'
        no file '/usr/local/share/lua/5.1/tds/init.lua'
        no file '/root/.luarocks/lib/lua/5.1/tds.so'
        no file '/root/torch/install/lib/lua/5.1/tds.so'
        no file '/root/torch/install/lib/tds.so'
        no file './tds.so'
        no file '/usr/local/lib/lua/5.1/tds.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'error'
        /root/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        preprocess.lua:1: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

**Comment by srush** [comment]
We recently added a dependency to `tds` and did not update the docker image yet. 

Can you run `luarocks install tds` and try again?

**Comment by wsnooker** [comment]
Thanks, the error disappear after installing the tds, and now the project runs correctly.

**Comment by akuckartz** [comment]
:+1:

**Comment by srush** [comment]
Let's keep this open until I fix it.
