### ISSUE TITLE
Logger Trouble when using log_level NOERROR

### ISSUE THREAD

**Issue by emartinezvic** [OpenNMT/OpenNMT#447]
OpenNMT crashes when using 

> translate.lua -model mymodel.t7 -src test.en -log_level NOERROR

It outputs the following error:

> /data/torch/install/bin/lua: ./onmt/utils/Logger.lua:179: attempt to compare nil with number
stack traceback:
    ./onmt/utils/Logger.lua:179: in function '_isVisible'
    ./onmt/utils/Logger.lua:71: in function 'log'
    ./onmt/utils/Logger.lua:113: in function 'info'
    ./onmt/translate/Translator.lua:132: in function '__init'
    /data/torch/install/share/lua/5.2/torch/init.lua:91: in function 'new'
    translate.lua:64: in function 'main'
    translate.lua:239: in main chunk
    [C]: in function 'dofile'
    /data/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
    [C]: in ?

It seems like in Logger.lua (line 61) the NOERROR value is missing.

**Comment by guillaumekln** [comment]
Thanks. I renamed this level to `NONE` but it is actually equivalent to `-disable_logs`.
