### ISSUE TITLE
Error when using learn_bpe

### ISSUE THREAD

**Issue by ykasimov** [OpenNMT/OpenNMT#456]
Hi all

I am trying to learn a BPE from a tokenized text. 
I am using the docker. When I run 'th tools/learn_bpe.lua -save_bpe codes < file.tok'
I get the following error:

```
[12/11/17 15:52:28 INFO] Using on-the-fly 'space' tokenization for input	
[12/11/17 15:52:28 INFO] Building vocabulary from STDIN	
/root/torch/install/bin/luajit: ./tools/utils/tokenizer.lua:340: attempt to index field 'hookManager' (a nil value)
stack traceback:
	./tools/utils/tokenizer.lua:340: in function 'segmentor'
	tools/learn_bpe.lua:145: in function 'get_vocabulary'
	tools/learn_bpe.lua:297: in function 'main'
	tools/learn_bpe.lua:351: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
```

Could you please help me to fix it? Thanks

**Comment by guillaumekln** [comment]
Hello,

There are some ongoing changes that concern input preprocessing. It will be fixed soon.

We recommend using the latest tagged version for now (v0.9.5 as of now).

**Comment by ykasimov** [comment]
Thank you. It works.

**Comment by getao** [comment]
same problem. I used v0.96. What should I do?
