### ISSUE TITLE
Changing Source Dictionaries

### ISSUE THREAD

**Issue by zhongzho** [OpenNMT/OpenNMT#458]
Hi, does OpenNMT allow manually changing the source/target dictionaries generated at preprocessing stage, if yes, what is the command for doing it? Thanks a lot!

**Comment by guillaumekln** [comment]
Hello,

Are the `-src_vocab` and `-tgt_vocab` the options you are looking for? It allows using existing vocabularies (e.g. from another preprocessing) when preparing the data.

Also read http://opennmt.net/OpenNMT/data/preparation/#vocabularies.

**Comment by zhongzho** [comment]
Hi, thanks for replying:) I am looking for an option for me to add and remove dictionary tokens from  src_vocab and tgt_vocab, (in a way, it is a combination of automated dictionary and partial existing dictionary) and then use the modified version for training. Is there an option for it?

**Comment by guillaumekln** [comment]
No there is no option for that. You should generate a vocabulary and then extend it manually or with a script of your own.

**Comment by zhongzho** [comment]
I see, will do. Thanks!
