### ISSUE TITLE
what is the meaning of 'max_sent_length' in translate option?

### ISSUE THREAD

**Issue by chenwangliangguo** [OpenNMT/OpenNMT#47]
Form the options:
[Maximum sentence length. If any sequences in srcfile are longer than this then it will error out]

In my understanding, when the length of the source sentence is longer than this value, the translated output is error.

But when I went  into the code, i found it is more about the longest translated sentence which can be generated.   Is there anything wrong in my understanding? what is the actual meaning of the translate option: max_sent_length?

**Comment by da03** [comment]
Yes you are right, it is indeed the longest translated sentence that can be generated. We will fix that.

**Comment by guillaumekln** [comment]
This will be part of #48.
