### ISSUE TITLE
nil value when detokenization

### ISSUE THREAD

**Issue by silverguo** [OpenNMT/OpenNMT#472]
Hi, 

I meet a problem when using rest_server,

the model is trained by latest commit,

and start a rest server as described in documentation,
```bash
th tools/rest_translation_server.lua -model XXX.t7 -replace_unk -log_level DEBUG
```

when I sent the request, following error,
```
tools/rest_translation_server.lua:105: unicode error in line tools/rest_translation_server.lua:98: attempt to index field 'preds' (a nil value)
```

I could get correct result when using **translate.lua**

if I switch to an early commit 88bc400c1b151d97e877710db11a304e64822a31, problem solved

so I guess the problem maybe related to a recent commit for rest server

Thanks!

**Comment by jsenellart** [comment]
thanks for reporting. this has been fixed in #475
