### ISSUE TITLE
nil hookManager in tokenizer.lua

### ISSUE THREAD

**Issue by silverguo** [OpenNMT/OpenNMT#478]
Hi, 

with the latest commit 56e80f6a0f39fc6267a6af11626705b7e53add5a, when I start a multi model server,
```bash
th tools/rest_multi_models.lua -model_config en2fr/server/rest_config.yml -port 9201
```

an error if sending the request,
```bash
Error in application: tools/rest_multi_models.lua:113: unicode error in line ./tools/utils/tokenizer.lua:340: attempt to index field 'hookManager' (a nil value)
```

no such problem with ***rest_translation_server.lua***

hookManager is not included in global variable ?

PS: my text is already tokenized before sending to the server, so I choose space for mode

Thanks!

**Comment by jsenellart** [comment]
Hi @silverguo - let me know if this works.

**Comment by silverguo** [comment]
Hi, 
@jsenellart 11f20f9 is an empty commit ?

**Comment by jsenellart** [comment]
strange - yes. #480 is the one.

**Comment by silverguo** [comment]
problem solved, thanks 👍
