### ISSUE TITLE
Could training process be accelerated by using GPU?

### ISSUE THREAD

**Issue by ljy296566** [OpenNMT/OpenNMT#487]
Could training process be accelerated by using GPU?

**Comment by guillaumekln** [comment]
Of course. Most people are exclusively using GPUs.

**Comment by ljy296566** [comment]
how to use GPU ?

**Comment by guillaumekln** [comment]
Please read the documentation. It is even part of the quickstart guide:

> You can also add -gpuid 1 to use (say) GPU 1.

http://opennmt.net/OpenNMT/quickstart/

**Comment by ljy296566** [comment]
Thanks a lot.
