### ISSUE TITLE
How to improve translation accuracy?

### ISSUE THREAD

**Issue by mewturn** [OpenNMT/OpenNMT#490]
Hi, I am currently trying to use OpenNMT to translate from simplified Chinese to English, and I have trained a model comprising 25,000 sentences for 13 epochs.

For segmenting the Chinese sentences, I used this segmenter: https://github.com/fxsjy/jieba

I have also removed all punctuations from both data sets.

After 13 epochs, no matter what data I feed into translate.lua, the model predicts with only a combination of six English words, ('a', 'and', 'I', 'the', 'to', 'we').
![image](https://user-images.githubusercontent.com/10064434/34856563-b749a994-f780-11e7-9782-69fa4db34cd7.png)

Are there any suggestions as to how I can improve the model's training accuracy?

Also, the reason why I am only using 25,000 sentences is that the program gets "Killed" if I use more than that. Is this issue caused by the lack of memory or something else?

**Comment by guillaumekln** [comment]
Hello,

Unfortunately 25,000 sentences is not enough to train a NMT system, you should use more data (at least x10).

How much system memory do you have?

**Comment by mewturn** [comment]
Hi,

I started using my laptop which can train 100,000 sentences with a GPU (2GB memory) and the results are much better now.

Will continue to increase the number of sentences.

Thanks!
