### ISSUE TITLE
How to evaluate exsiting model with other metric?

### ISSUE THREAD

**Issue by ljy296566** [OpenNMT/OpenNMT#491]
I train the model with default validation metric `perplexity `, and now I want to evaluate the existing model with BLEU. I read the document about `tools/score.lua`, but I still don't understand how to use the command 
`$ th tools/score.lua REFERENCE [-sample SN] [-scorer bleu|ter|dlratio] PARAMS < OUT`
could anyone help me ?

**Comment by ljy296566** [comment]
I sincerely hope someone could help me.

**Comment by guillaumekln** [comment]
As described in the usage:

```
th tools/score.lua reference.txt -scorer bleu < predictions.txt
```

Replace `reference.txt` and `predictions.txt` by your own file.

**Comment by ljy296566** [comment]
Thanks a lot, the command works. 
But the command does not specify a model, which model does it evaluate ?

**Comment by guillaumekln** [comment]
You should first translate your test file using `translate.lua`.

**Comment by ljy296566** [comment]
Thanks, I got it.
