### ISSUE TITLE
Error at translation

### ISSUE THREAD

**Issue by zhongzho** [OpenNMT/OpenNMT#492]
I have an error at translation: 
translate.lua:255: attempt to index local 'outFile' (a nil value)

Anyone knows how to solve this issue? Thanks!

**Comment by guillaumekln** [comment]
Which version or commit ID are you using and what is the command you ran?

**Comment by jsenellart** [comment]
there was no handling of errors for several io.open statement and this was causing the reported problem if `-out` file could not be open for writing. There is now a proper error message.
