### ISSUE TITLE
Inference result is not deterministic when decoding with a language model.

### ISSUE THREAD

**Issue by getao** [OpenNMT/OpenNMT#495]
Hi, I used OpenNMT to train a seq2seq model and an RNN langauge model.

When I try to generate prediction for a test instance, I loaded the trained seq2seq model as well as the language model with the option "-lm_model".

However, I found the prediction for the same test instance is not determinstic, in other words, sometimes I will get prediction_sentence1 but sometimes I will get prediction_sentence2. Also, it is observed that the PRED SCORE for the same instance is not fixed using the same model and options after I did the inference for multiple times.

Can you help me on this issue? Thanks.

-----Update------
I found that the problem is from the language model scorer. I used the language model to score the same sentence but everytime I got different scores. Why?

**Comment by getao** [comment]
Thank you, it seems that I should disable dropout. So, is there any way to disable dropout for that?

**Comment by guillaumekln** [comment]
Hello,

It should be fixed on the master. Some noise were still applied during inference.
