### ISSUE TITLE
"invalid argument: -output" during quickstart (preprocessing)

### ISSUE THREAD

**Issue by pltrdy** [OpenNMT/OpenNMT#51]
Following the [guide](http://opennmt.net//Guide/) i tried to preprocess the data using:
`
th preprocess.lua -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -output data/demo`

And got the following error:
```
invalid argument: -output	
Usage: [options] 

preprocess.lua

**Preprocess Options**


  -config                 Read options from this file []
  -train_src              Path to the training source data []
  -train_tgt              Path to the training target data []
  -valid_src              Path to the validation source data []
  -valid_tgt              Path to the validation target data []
  -save_data              Output file for the prepared data []
  -src_vocab_size         Size of the source vocabulary [50000]
  -tgt_vocab_size         Size of the target vocabulary [50000]
  -src_vocab              Path to an existing source vocabulary []
  -tgt_vocab              Path to an existing target vocabulary []
  -features_vocabs_prefix Path prefix to existing features vocabularies []
  -src_seq_length         Maximum source sequence length [50]
  -tgt_seq_length         Maximum target sequence length [50]
  -shuffle                Shuffle data [1]
  -seed                   Random seed [3435]
  -report_every           Report status every this many sentences [100000]
```

`pltrdy`

**Comment by srush** [comment]
Good catch. The parameter is now called "-save_data" I changed the Guide.

**Comment by pltrdy** [comment]
Also note you have deadlinks in http://opennmt.net//Guide/#step-1-preprocess-data & step 2

- In  **Step 1: Preprocess Data**: 
  - *text:* options
  - *target:* http://opennmt.net/OpenNMT/Options#preprocess

 - In **Step 2: Train the model**:  
   - *text:* option
   - *target:* http://opennmt.net/OpenNMT/Options#train

**Comment by srush** [comment]
All fixed now.

**Comment by pltrdy** [comment]
Also, the 3rd step isnt up to date:

From the [guide](http://opennmt.net//Guide/#step-3-translate):   
`th translate.lua -model demo-model_final.t7 -src data/src-val.txt -src_dict data/demo.src.dict -tgt_dict data/demo.tgt.dict`

From the [doc on github](https://github.com/OpenNMT/OpenNMT/blob/master/doc/Quickstart.md#step-3-translate):
` th translate.lua -model demo-model_epochX_PPL.t7 -src data/src-test.txt -output pred.txt`

I guess this means that `translate.lua` now 'automatically' looks for dictionaries in `./data/` path, right?


(tell me if reporting those minor errors here is relevant. I personally do not mind with it, but some people maybe could)

**Comment by srush** [comment]
Keep them coming this is fantastically helpful. 

translate just stores the dictionaries internally now.

**Comment by colorprint** [comment]
Same typos with model_final.t7 in README.md
