### ISSUE TITLE
How to deal with huge amounts of training data

### ISSUE THREAD

**Issue by getao** [OpenNMT/OpenNMT#514]
Hello. I wonder if there is a way to deal with huge amounts of training data which is too large to be fully loaded into memory.

**Comment by shahbazsyed** [comment]
You can either try using smaller batch sizes, limit the maximum length of the sequences or a limited vocabulary size. It is always better to provide some more details on your training data such as the number of examples, average length, your use case etc.,

**Comment by getao** [comment]
Thanks, @shahbazsyed . But the problem is that my training set is too large. I even generate load the files to generate .t7 file using preprocess.lua

**Comment by jsenellart** [comment]
Hello, the best is to use dynamic dataset exactly meant for that and for which you don't have upper limits - see http://forum.opennmt.net/t/dynamic-dataset/746/31 and http://opennmt.net/OpenNMT/training/sampling/#dynamic-dataset.

**Comment by getao** [comment]
@jsenellart  Thanks. It's exactly what I want
