### ISSUE TITLE
Is there any way to use model ensemble for prediction?

### ISSUE THREAD

**Issue by getao** [OpenNMT/OpenNMT#516]
Hello, I wonder if there is a way to conduct model ensemble for inference, which usually can get better results.

Thanks,

**Comment by jsenellart** [comment]
Hello @getao - we have it on a branch, see #300. We have not merged because were not convinced about the gain - but let us know if you have any positive results and we can reconsider.

**Comment by guillaumekln** [comment]
You can also take a look at [`tools/average_models.lua`](https://github.com/OpenNMT/OpenNMT/blob/master/tools/average_models.lua). We found this could lead to the same performance gain as ensembling.

**Comment by getao** [comment]
Thank you very much. @jsenellart  @guillaumekln
