### ISSUE TITLE
The definition of the score outputted by lm.lua score

### ISSUE THREAD

**Issue by getao** [OpenNMT/OpenNMT#518]
Hello, I am not very sure the definition of the score outputted by lm.lua score. I thought it is the log likelihood of a sentence but it is a positive number. So, is it the perplexity defined at http://opennmt.net/OpenNMT/training/logs/ ??? Is it the sentence-level or word-level (normalized to the sentence's length) ???

_____update______
I have checked the codes for computing the LM score. It seems that the outputted score is the negative log probability normalized to the sentence length (i.e., cross entropy). Can you help confirm it? 

Additional question: are log() and exp() used in OpenNMT based on e (Natural logarithm)?

Thanks in advance!

**Comment by guillaumekln** [comment]
> It seems that the outputted score is the negative log probability normalized to the sentence length (i.e., cross entropy).

This is correct.

> Additional question: are log() and exp() used in OpenNMT based on e (Natural logarithm)?

Also correct.
