### ISSUE TITLE
Problems with setting up lua server in latest docker image

### ISSUE THREAD

**Issue by HuiyingLi** [OpenNMT/OpenNMT#526]
I pulled the latest opennmt/opennmt:latest docker image and tries to set up a service as in the documentation. With the fresh image, luarocks will throw the following errors:
```
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/torch/rocks/master - Failed downloading https://raw.githubusercontent.com/torch/rocks/master/manifest - /root/.cache/luarocks/https___raw.githubusercontent.com_torch_rocks_master/manifest
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master - Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest - /root/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master/manifest

Error: No results matching query were found.

```
This is because the latest image is very basic and misses several tools for installing xavante, which can be fixed by:
```
apt-get update
apt-get install -y wget unzip gcc
```
Maybe you can add them into the image?

**Comment by guillaumekln** [comment]
I pushed a new image containing the `restserver-xavante` rock. Would that be enough for you?

We are trying to keep the Docker image slim.

**Comment by HuiyingLi** [comment]
@guillaumekln Thank you!
Yeah I understand you want to keep it slim. I can build image locally too, and I greatly appreciate your help!
