### ISSUE TITLE
Question: transfer learning

### ISSUE THREAD

**Issue by yapingzhao** [OpenNMT/OpenNMT#529]
I am newbie of opennmt. The library is very helpful for me. And I have some questions.
I want to apply a transfer learning strategy in neural machine translation.

First, translate models using large-scale parallel corpus training. but, How can I get model parameter weight?
Then, how do I transfer the weights of the parameters to the new translation framework (opennmt)?
Looking forward to your advice or answers.
Best regards,

yapingzhao

**Comment by guillaumekln** [comment]
The answer is the same as OpenNMT-py, let's keep the discussion there: https://github.com/OpenNMT/OpenNMT-py/issues/644
