### ISSUE TITLE
Cannot use `translate.lua` without `-gpuid`

### ISSUE THREAD

**Issue by pltrdy** [OpenNMT/OpenNMT#53]
Hi,

# `translate.lua` without `-gpuid`
Following the [guide on github](https://github.com/OpenNMT/OpenNMT/blob/master/doc/Quickstart.md#step-3-translate)(some differences has been [noticed and reported](https://github.com/OpenNMT/OpenNMT/issues/51#issuecomment-270903114) between [doc on github](https://github.com/OpenNMT/OpenNMT/blob/master/doc/Quickstart.md#step-3-translate) and [opennmt.net](http://opennmt.net//Guide/#step-3-translate)), i ran:

`th translate.lua <some_path>.t7 -src <data_path>.txt -output pred.txt`
which gives:
```
Loading '<path>.t7'...                             
/home/<user>/torch/install/bin/luajit: /home/<user>/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <torch.CudaTensor>
stack traceback:
  [C]: in function 'error'
  /home/<user>/torch/install/share/lua/5.1/torch/File.lua:343: in function 'readObject'
  /home/<user>/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
  /home/<user>/torch/install/share/lua/5.1/nn/Module.lua:184: in function 'read'
  /home/<user>/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
  /home/<user>/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
  /home/<user>/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
  /home/<user>/torch/install/share/lua/5.1/torch/File.lua:353: in function 'readObject'
  /home/<user>/torch/install/share/lua/5.1/torch/File.lua:368: in function 'readObject'
  /home/<user>/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
  /home/<user>/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
  ...
  /home/<user>/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
  /home/<user>/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
  /home/<user>/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
  ./onmt/translate/Translator.lua:29: in function '__init'
  /home/<user>/torch/install/share/lua/5.1/torch/init.lua:91: in function 'new'
  translate.lua:65: in function 'main'
  translate.lua:193: in main chunk
  [C]: in function 'dofile'
  ...<user>/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
  [C]: at 0x00406670
```
# `translate.lua` with `-gpuid 1`
`th translate.lua <some_path_>.t7 -src <data_path>.txt -output pred.txt -gpuid 1`
It runs! :)  

For sure I want to run with GPU, still, I'm not sure if this is related to my setup, if its an actual issue or an undocumented requirement.

Hope it helps
`pltrdy`

**Comment by guillaumekln** [comment]
If the model was trained on the GPU, you then need to load it on the GPU and specify the `-gpuid` option.

You can use the [`tools/release_model.lua`](https://github.com/OpenNMT/OpenNMT/tree/master/tools#release-model) script to make it work on the CPU so you don't need to set the `-gpuid` option.

**Comment by pltrdy** [comment]
Ok my bad then. I thought about it just after posting.
Thanks for the clarification. 
Closing.
