### ISSUE TITLE
Bug in preprocessing. It creates only two shards. a small and a huge (3GB) one.

### ISSUE THREAD

**Issue by nimas62** [OpenNMT/OpenNMT#530]
Linux Debian,
Python 3.5
cuda 9.0.
pytorch 0.3.1
OpenNMTpy  (last version as of March 2nd)

I use the CNNDM dataset separated in txt files for train, validation, and test. The training set more than 500 MB. When I perform preprocessing on it, with any max_shard_size ranging from 50 MB to 500 MB, it generates only two shards, which are 200 MB and 3.7 Gigabytes! If I pass this procedure successfully, at last training will fail when loading the second huge preprocessed file (data.train2.pt). I will include the error log here. I can't figure out where is the bug. I have checked textdataset and io modules. I appreciate any piece of help.

Loading train dataset from /home/usuaris/veu4/masterveu2/OpenNMT/data/summarizer.train.2.pt, number of examples: 271582
/pytorch/torch/lib/THC/THCTensorIndex.cu:360: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = false]: block: [1,0,0], thread: [64,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
.
.
.
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.c line=36 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "train.py", line 438, in <module>
    main()
  File "train.py", line 430, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "train.py", line 252, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/home/usuaris/veu/masterveu2/EnvPy3/OpenNMT-py/onmt/Trainer.py", line 178, in train
    report_stats, normalization)
  File "/home/usuaris/veu/masterveu2/EnvPy3/OpenNMT-py/onmt/Trainer.py", line 311, in _gradient_accumulation
    trunc_size, self.shard_size, normalization)
  File "/home/usuaris/veu/masterveu2/EnvPy3/OpenNMT-py/onmt/Loss.py", line 123, in sharded_compute_loss
    loss, stats = self._compute_loss(batch, **shard)
  File "/home/usuaris/veu/masterveu2/EnvPy3/OpenNMT-py/onmt/modules/CopyGenerator.py", line 191, in _compute_loss
    batch, self.tgt_vocab, self.cur_dataset.src_vocabs)
  File "/home/usuaris/veu/masterveu2/EnvPy3/OpenNMT-py/onmt/io/TextDataset.py", line 115, in collapse_copy_scores
    index = batch.indices.data[b]
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCStorage.c:36

**Comment by guillaumekln** [comment]
Looks like you opened this issue on the wrong repository. Go to https://github.com/OpenNMT/OpenNMT-py instead.

**Comment by nimas62** [comment]
You're right. Thank you. Please delete the thread.
