### ISSUE TITLE
Send a string as input instead of file on translate.lua

### ISSUE THREAD

**Issue by grlouk** [OpenNMT/OpenNMT#533]
Hello everyone! I am new to lua and I am wondering if I can send on th translate.lua -src a string and not a file where the string exists. I have searched a lot before posting but I could not manage to find something similar. My main problem is that Machine Translation is getting slower because I have to read/open from files. Thank you in advance!

**Comment by grlouk** [comment]
Hello,
yes i think opening and reading from file duplicates the actual time.
For example the main service needs 2 seconds to communicate reach the translate.lua and send back the response and transalte.lua needs 2-3 more seconds to finish.

**Comment by guillaumekln** [comment]
Is the server running?

**Comment by grlouk** [comment]
yes but i cannot find the default port (7784) on listen or established list

**Comment by panosk** [comment]
When you start the server, try to define the host as 0.0.0.0.

**Comment by grlouk** [comment]
efcharisto an kai den prepei na einai kati tetoio.

**Comment by grlouk** [comment]
Does after installation need any action to make rest server run or after success installation it is ready?

**Comment by guillaumekln** [comment]
Did you follow the documentation I linked above?

**Comment by grlouk** [comment]
After running the command between the 2 steps I receive : 
module 'onmt.init' not found:No LuaRocks module found for onmt.init

**Comment by grlouk** [comment]
After many attempts I receive this:

/home/xxx/torch/install/bin/luajit: cannot open /home/xxx/torch/install/rest_translation_server.lua: No such file or directory
stack traceback:
        [C]: in function 'dofile'

**Comment by guillaumekln** [comment]
I'm not sure what you are trying to do. Just go inside the OpenNMT directory and run:

```bash
th tools/rest_translation_server.lua -h
```

**Comment by grlouk** [comment]
@guillaumekln 
I am receiving this:
torch/install/rest_translation_server.lua:16: attempt to index global 'onmt' (a nil value)

**Comment by guillaumekln** [comment]
You should stick to the documentation:

1. http://opennmt.net/OpenNMT/installation/#standard
2. http://opennmt.net/OpenNMT/tools/servers/#rest

**Comment by grlouk** [comment]
Finally, for helping future users .luarocks must be erased when installing OpenNMT and after that we have to install luarocks inside OpenNMT folder.
