### ISSUE TITLE
Segmentation fault in preprocess

### ISSUE THREAD

**Issue by fodilB** [OpenNMT/OpenNMT#547]
th  preprocess.lua --size 5000 -train_src data/src-train.txt  -train_tgt data/tgt-train.txt -tgt_vocab_size 5000 -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt  -save_data data/demo 

Erreur de segmentation (core dumped)

**Comment by guillaumekln** [comment]
How did you install Torch? There might be an issue with your installation.

**Comment by himanshudce** [comment]
same error please solve. and i also tried reinstalling pytorch nothing happend

**Comment by guillaumekln** [comment]
> same error please solve. and i also tried reinstalling pytorch nothing happend

This is the Torch implementation. As said above, this is most likely an installation issue.

**Comment by anderleich** [comment]
Solved it!

1- Install Torch
git clone https://github.com/torch/distro.git ~/torch --recursive
cd ~/torch; bash install-deps;
./install.sh
source ~/.bashrc
luarocks install tds
luarocks install bit32

2-OpenNMT
git clone https://github.com/OpenNMT/OpenNMT
cd OpenNMT
