### ISSUE TITLE
Meet with lua:446:'for' limit must be a number

### ISSUE THREAD

**Issue by linhy1993** [OpenNMT/OpenNMT#554]
When I start to train my model, it did not work.
install/bin/lua: ./onmt/modules/Decoder.lua:446: 'for' limit must be a number
stack traceback:
	./onmt/modules/Decoder.lua:446: in function 'forwardAndApply'
	./onmt/modules/Decoder.lua:509: in function 'forward'
	./onmt/Seq2Seq.lua:211: in function 'trainNetwork'
	./onmt/train/Trainer.lua:185: in function '__init'
	/Users/linhongyi/torch/install/share/lua/5.2/torch/init.lua:91: in function 'new'
	train.lua:332: in function 'main'
	train.lua:338: in main chunk
	[C]: in function 'dofile'
	...ngyi/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk

No GPU, just using mac

**Comment by guillaumekln** [comment]
Please update to the latest version. This has been fixed, see #551.

**Comment by linhy1993** [comment]
Thank you. It works!
