### ISSUE TITLE
Difference between using epoch and train_steps

### ISSUE THREAD

**Issue by starnleymbote** [OpenNMT/OpenNMT#555]
What affects the choice of my training to switch from using epoch to train_steps..could it be the machine architecture?

Is there any effect in the performance of my models or simply said will there be any difference in the model if I choose to use the epoch approach n forgo the train_step to train let's say model x compared to using train_steps n forgo the epoch to train model x also.

**Comment by guillaumekln** [comment]
This version of OpenNMT can only work with epochs. Are you talking about OpenNMT-py instead?

**Comment by starnleymbote** [comment]
yes exactly OpenNMT-py

**Comment by guillaumekln** [comment]
You should open an issue on this project instead. Thanks.
