### ISSUE TITLE
Difference bteween gnmt and brnn encoder

### ISSUE THREAD

**Issue by Anupama94** [OpenNMT/OpenNMT#556]
Hi,

Could you please explain to me the difference between the two encoders gnmt and brnn encoders. I know that in the gnmt encoder only the first layer is bidirectional. This has been done so to increase the ability of parallelization isn't it? Is it possible that a 2-layer gnmt encoder could give better translations than when a  2-layer brnn encoder is used?

Thank you.

**Comment by guillaumekln** [comment]
Hello,

> I know that in the gnmt encoder only the first layer is bidirectional.

That is the difference.

> Is it possible that a 2-layer gnmt encoder could give better translations than when a 2-layer brnn encoder is used?

It depends on the dataset and optimizer. However, BRNN has more parameters than GNMT for the same number of layers so it should perform better when the training data is large.

**Comment by Anupama94** [comment]
Understood! Thanks a lot.
