### ISSUE TITLE
Multiple same sentences in  beam search n_best output

### ISSUE THREAD

**Issue by wsnooker** [OpenNMT/OpenNMT#56]
I trained a homology MT model using opennmt. The translated results contain multiple same outputs when i set n_best to 3 in translate.lua. As follows (chinese characters), you could see the print_log of BEST HYP,  same hypothesis but different pred scores.  Are there some parameters i miss in the decoding stage? 

SENT 5: 毛 细 血管 血栓 吃 什么 药
PRED 5: 毛 细 血管 血栓 吃 什么 药 好
PRED SCORE: -1.8767

BEST HYP:
[-1.8767] 毛 细 血管 血栓 吃 什么 药 好
[-3.4304] 毛 细 血管 血栓 吃 什么 药
[-3.6762] 毛 细 血管 血栓 吃 什么 药

SENT 6: 发电 机 纵轴 和 横轴
PRED 6: <unk> 发电 机
PRED SCORE: -2.6976

BEST HYP:
[-2.6976] <unk> 发电 机
[-2.8108] <unk> 发电 机
[-3.7468] <unk> 发电 机

**Comment by guillaumekln** [comment]
There is a revised implementation of the beam search that is coming very soon. It should fix some issues.

**Comment by srush** [comment]
This is the PR if you want to try it out now https://github.com/OpenNMT/OpenNMT/pull/48

**Comment by wsnooker** [comment]
OK, sure to try it.
