### ISSUE TITLE
unicode issue for translating Bangla to English

### ISSUE THREAD

**Issue by AridHasan** [OpenNMT/OpenNMT#567]
Hi,
While I'm translating Bangla to English I'm getting an error that is showing only Unicode numbers instead of showing Bangla characters.
SENT 810: [u'\u0986\u09ae\u09b0\u09be', u'\u099c\u09be\u09a8\u09bf', u'\u09af\u09c7', u'\u09b8\u09c7', u'\u09b2\u09c7\u0995\u09cd\u09b8\u09bf\u09a8\u09cd\u099f\u09a8', u'\u098f\u09b0', u'\u09b0\u09be\u09ae\u09be\u09a6\u09be', u'\u0987\u09a8', u'\u098f', u'\u09af\u09be\u0993\u09df\u09be\u09b0', u'\u09aa\u09b0\u09bf\u0995\u09b2\u09cd\u09aa\u09a8\u09be', u'\u0995\u09b0\u09c7\u099b\u09c7\u09a8\u0964']

**Comment by guillaumekln** [comment]
Hi,

How does the output in `pred.txt` look like?

**Comment by AridHasan** [comment]
Hi,

It doesn't generate anything. ```pred.txt``` is empty.
