### ISSUE TITLE
Failed to train the model following the instructions: No module named onmt.IO

### ISSUE THREAD

**Issue by stunFantasy** [OpenNMT/OpenNMT#574]
Following the instructions on http://opennmt.net/OpenNMT-py/im2text.html,
after running 
```bash
python train.py -model_type img -data data/im2text/demo -save_model demo-model -gpu_ranks 0 -batch_size 20 -max_grad_norm 20 -learning_rate 0.1 -word_vec_size 80 -encoder_type brnn -image_channel_size 1
```
I got an error saying "ImportError: No module named onmt.IO."

Anybody knows why? Thank you!

Besides, I don't think current repository can be successfully executed by following the instructions on the website above.

The file: OpenNMT-py/onmt/inputters/inputter.py 780 line:
```python
glob.glob(opt.data + '.' + corpus_type + '.[0-9]*.pt')))
```

The preprocessing will generate multiple demo.*.pt files, but the regular expression in this line seems to be wrong.(a redundant '.'?)

**Comment by tkngoutham** [comment]
How did this issue got resolved ?
