### ISSUE TITLE
Error with tokenization when given an alphanumeric (aggressive/sep_annotate)

### ISSUE THREAD

**Issue by jungikim** [OpenNMT/OpenNMT#59]
Given an alphanumeric word (one or more letters followed by one or more numbers), tokenizer  produces erroneous tokens when options -mode aggressive and -sep_annotate are set.

`echo "MP3" | th tools/tokenize.lua -mode aggresive -sep_annotate`
`MP MP￭3`

**Comment by guillaumekln** [comment]
Thanks for reporting! The commit above fixed it.

**Comment by jungikim** [comment]
And thank you for fixing it so quickly :-)
