### ISSUE TITLE
weird output

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/OpenNMT#60]
Is this some kind of a flaw because of the input ending with a "," ?
if so, the output is cut on what rule ? max sentence length ?

thanks.

SENT 635: As an analyst anxious about a familiar strangeness , he wanders in a forest of symbols , stops after each step to examine an object in the form of a puzzle , tormented by irritating questions ,	
PRED 635: <unk> soucieux d ' un <unk> familier , il s ' est <unk> dans une forêt de symboles , s ' arrête après chaque étape d ' un puzzle , sous la forme d ' un puzzle , tourmenté par des questions <unk> , <unk> par des questions <unk> , <unk> par des questions <unk> , <unk> par des questions <unk> , <unk> par des questions <unk> , <unk> par des questions <unk> , <unk> par des questions <unk> , <unk> par des questions <unk> , <unk> par des questions <unk> , <unk> par des questions <unk> , <unk> par des questions <unk> , <unk> par des questions <unk> , <unk> par des questions <unk> , <unk> par des questions <unk> , <unk> par des questions <unk> , <unk> par des questions <unk> , <unk> par des questions <unk> , <unk> par des questions <unk> .

**Comment by guillaumekln** [comment]
It could be an issue as the model probably learned that the comma is followed by words.

The output is indeed cut based on sentence length. See the option `-max_sent_length`.
