### ISSUE TITLE
Question related to the Arabic Dataset

### ISSUE THREAD

**Issue by wael34218** [OpenNMT/OpenNMT#63]
In the [demo](https://demo-pnmt.systran.net/production#/translation), the Arabic-English translation is very accurate. It can also translate different dialects. I was wondering how can I get the dataset (parallel corpora) you used to train it. Is it open for the public? Or can I purchase it?

**Comment by srush** [comment]
I think that systran's data sources may be proprietary. However there is lots of great Arabic-English data online. For instance, http://opus.lingfil.uu.se/  has about 55 million sentences.

**Comment by wael34218** [comment]
Thanks
