### ISSUE TITLE
HOWTO on using -phrase_table option needed

### ISSUE THREAD

**Issue by nkrot** [OpenNMT/OpenNMT#65]
Would be great to have a comment on **the format of the resource file for -phrase_table option** , as promised in the help message of `translate.lua`.  I have tried the following but it does not seem to work when translating from English to German using the model from [http://opennmt.net//Models/]

> probation period|||Probezeit
> employment duty|||Tätigkeit

Additional comments on letter case in the phrase table and some details of the substitution algorithms would be appreciated as well.

**Comment by guillaumekln** [comment]
I added some details on the phrase table in [the guide](http://opennmt.net//Guide/#translating-unk-words). Thank you for the feedback.

Please note that it can only replace **single** tokens at the moment. The entries are also case sensitive.

**Comment by nkrot** [comment]
Thx! Replacing single tokens works indeed.

Do you plan implementing substitution of contiguous sequences of <unk>? To fix the cases as follows:

> probation period|||Probezeit

With English to German translation it will be a frequent case.

**Comment by guillaumekln** [comment]
No plan to support this at the moment as the model is token based.

However, you could try adding these translation in your training data.
