### ISSUE TITLE
Simpler cloning?

### ISSUE THREAD

**Issue by swiseman** [OpenNMT/OpenNMT#69]
This may be controversial, but can't we just do the per-timestep cloning in Sequencer with 
```network:clone('weight', 'gradWeight', 'bias', 'gradBias')```

In my experience this leads to much faster creation of clones (and gives the same results). Here's a PR that does this: https://github.com/OpenNMT/OpenNMT/pull/67

**Comment by guillaumekln** [comment]
Merged.
