### ISSUE TITLE
Link to de-en model is broken

### ISSUE THREAD

**Issue by nkrot** [OpenNMT/OpenNMT#71]
The link to German->English pretrained model, as found on http://opennmt.net/Models/ page, is broken:

https://s3.amazonaws.com/opennmt-models/onmt_baseline_wmt15-all.de-en_epoch13_8.98_release.t7

I am eager to try it. But... Is the model file available under a different URL?

**Comment by vince62s** [comment]
fixed.

**Comment by guillaumekln** [comment]
Here is the direct link:

https://s3.amazonaws.com/opennmt-models/onmt_baseline_wmt15-all.de-en_epoch13_8.98_release.t7
