### ISSUE TITLE
Can CNN buffers be shared ?

### ISSUE THREAD

**Issue by helson73** [OpenNMT/OpenNMT#73]
I'm interested in if CNN is included in sequencer module, could its gradInput and output buffers be shared along clones ? (assume memory pre-allocation is enabled.)
For instance, nn.SpatialConvolution, nn.SpatialMaxPooling and their cudnn alternatives.

**Comment by guillaumekln** [comment]
`gradInput` tensors can always be shared unless they are exposed outside the network but the code handles that for you.

`output` tensors can be shared if they are not used in the backward pass. You should take a look at the implementation of every new modules you introduce in the code and apply this rule:

1. If the content of `input` is used in `updateGradInput` or `accGradParameters`, add the module in the `protectInput` table.
2. If the content of `self.output` is used in `updateGradInput` or `accGradParameters`, add the module in the `protectOutput` table.

For example, see the modules that are already blacklisted in [`MemoryOptimizer.lua`](https://github.com/OpenNMT/OpenNMT/blob/master/onmt/utils/MemoryOptimizer.lua) and how they use their input or output in the backward pass.

It forces you to know in details the modules you used but the optimization is efficient.

**Comment by helson73** [comment]
@guillaumekln Thank you so much!
