### ISSUE TITLE
Teacher forcing

### ISSUE THREAD

**Issue by hrishikeshvganu** [OpenNMT/OpenNMT#74]
I wanted to implement teacher forcing as in [Pascanau et. al. JMLR](http://www.jmlr.org/proceedings/papers/v28/pascanu13.pdf) so that we feed in the predicted previous label $y_hat_{t}$ instead of the ground-truth label $y_{t}$  . Any plans for adding this feature? I can work on the code if you provide pointers.

Note: I don't know lua but am willing to try if I get some pointers

**Comment by guillaumekln** [comment]
Let's discuss this feature on the forum:

http://forum.opennmt.net/t/teacher-forcing/104
