### ISSUE TITLE
Log error occured in training start

### ISSUE THREAD

**Issue by wsnooker** [OpenNMT/OpenNMT#81]
/root/torch/install/bin/luajit: ./onmt/utils/Log.lua:7: attempt to call method 'write' (a nil value)
stack traceback:
        ./onmt/utils/Log.lua:7: in function 'logJsonRecursive'
        ./onmt/utils/Log.lua:27: in function 'logJson'
        train.lua:516: in function 'main'
        train.lua:554: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

**Comment by da03** [comment]
Oh my bad. There is a typo in Logger.lua. Thanks for reporting it!

**Comment by wsnooker** [comment]
Be waiting for merging it.
