### ISSUE TITLE
Add the validation perplexity

### ISSUE THREAD

**Issue by wsnooker** [OpenNMT/OpenNMT#85]
The traning print log dose not contain validation perplexity, add it may be better.
 
> Epoch 1 ; Iteration 10/183 ; Learning rate 1.0000 ; Source tokens/s 196 ; Perplexity 157766.75
> Epoch 1 ; Iteration 20/183 ; Learning rate 1.0000 ; Source tokens/s 318 ; Perplexity 138999.74
> Epoch 1 ; Iteration 30/183 ; Learning rate 1.0000 ; Source tokens/s 415 ; Perplexity 174117.53
> Epoch 1 ; Iteration 40/183 ; Learning rate 1.0000 ; Source tokens/s 491 ; Perplexity 619423.11

**Comment by da03** [comment]
Hmm currently OpenNMT evaluates on validation data and logs validation perplexity when an epoch ends. (https://github.com/OpenNMT/OpenNMT/blob/master/train.lua#L413)

**Comment by wsnooker** [comment]
Oh, that's it. Thank you.
