### ISSUE TITLE
error in releasing model

### ISSUE THREAD

**Issue by wsnooker** [OpenNMT/OpenNMT#89]
`th tools/release_model.lua -model model/demo_epoch4_1503.07.t7 -output_model model/cdemo_epoch4_1503.07.t7  -gpuid 1`

>Loading model 'model/demo_epoch4_1503.07.t7'... 
... done.
Converting model...
/root/torch/install/bin/luajit: tools/release_model.lua:49: attempt to call method 'float' (a nil value)
stack traceback:
        tools/release_model.lua:49: in function 'main'
        tools/release_model.lua:60: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

**Comment by guillaumekln** [comment]
Can you share the options you used for training?

**Comment by wsnooker** [comment]
The training parameter was the default option in project demo. And I switch to release v0.2.0 branch, model conversion worked fine. Maybe I pushed something wrong in the master branch.

**Comment by wsnooker** [comment]
I pulled the new master branch and checked again, then `tools/release_model.lua` failed to convert GPU model to CPU model.

**Comment by guillaumekln** [comment]
Do you get the same error with the updated code?

I suspect your model was trained with `-brnn` and the version of `tools/release_model.lua` is older than ff48a96.
