### ISSUE TITLE
The model predicts only dot for each sentence.

### ISSUE THREAD

**Issue by bashartalafha** [OpenNMT/OpenNMT#90]
I set the number of epochs to 1 and then execute "th train.lua -data data/demo-train.t7 -save_model model".
After having the model which I can use to predict on new data, i ran "th translate.lua -model model_epoch1_2419.70.t7 -src data/src-test.txt -output pred.txt" for 5 sentences only in src-test.txt, and then I got only dots in the predictions like this:
.
.
.
.
.
P.S. I'm using  CPU only.

**Comment by guillaumekln** [comment]
Unfortunately you won't get any good results with the demo dataset, especially after one epoch. The model requires way more data to produce accurate translation.

If you want to experiment on a real dataset and have access to a GPU (for the training to finish in a reasonable amount of time), take a look at this tutorial:

http://forum.opennmt.net/t/training-english-german-wmt15-nmt-engine/29
