### ISSUE TITLE
Error in preprocessing

### ISSUE THREAD

**Issue by pshashk** [OpenNMT/OpenNMT#99]
```
th preprocess.lua -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo
/home/pshashkin/torch/install/bin/luajit: preprocess.lua:167: attempt to index local 'Vocabulary' (a nil value)
stack traceback:
	preprocess.lua:167: in function 'main'
	preprocess.lua:202: in main chunk
	[C]: in function 'dofile'
	...hkin/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
```

The latest working commit for me is e1fd0b8d6fbf117d4336f45f6abf98f873408071

**Comment by guillaumekln** [comment]
Did you update the whole project or just `preprocess.lua`?

This command line runs just fine on `master`.

**Comment by pshashk** [comment]
I've updated entire project from `master`.

**Comment by guillaumekln** [comment]
Did you previously install OpenNMT with `luarocks make rocks/opennmt-scm-1.rockspec`

**Comment by pshashk** [comment]
Yes, I did when I was testing translation server. Reinstalled OpenNMT with `luarocks make rocks/opennmt-scm-1.rockspec` and now everything works fine.
Thanks for help. Closing the issue.
